{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "DatasetMeaning",
        "value": "Historical research snapshot. Listing counts do not establish current availability or payment adoption."
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Listings\",\"Markets\",\"Services\",\"Review\",\"Changes\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "Listings_Markets",
        "fromColumn": "Market ID",
        "fromTable": "Listings",
        "toColumn": "Market ID",
        "toTable": "Markets"
      },
      {
        "name": "Listings_Services",
        "fromColumn": "Service ID",
        "fromTable": "Listings",
        "toColumn": "Service ID",
        "toTable": "Services"
      },
      {
        "name": "AutoDetected_aa907566-7c13-4b46-90ad-4eabe0b626bd",
        "fromColumn": "market_id",
        "fromTable": "Changes",
        "toColumn": "Market ID",
        "toTable": "Markets"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Listings",
        "columns": [
          {
            "name": "Listing ID",
            "dataType": "string",
            "lineageTag": "c46ef623-232b-434e-87d9-1aa80349ed4b",
            "sourceColumn": "listing_id",
            "summarizeBy": "none"
          },
          {
            "name": "Market ID",
            "dataType": "string",
            "lineageTag": "856b1593-7a1b-42f2-bc74-735714358de1",
            "sourceColumn": "market_id",
            "summarizeBy": "none"
          },
          {
            "name": "Market",
            "dataType": "string",
            "lineageTag": "59ef9ab8-911a-49c7-a463-89e0d2930f95",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "Service ID",
            "dataType": "string",
            "lineageTag": "d0a5dfe8-504b-44b0-8116-e02c5bf2a274",
            "sourceColumn": "service_id",
            "summarizeBy": "none"
          },
          {
            "name": "Service",
            "dataType": "string",
            "lineageTag": "a7030c02-02ec-4ea2-afd7-1d469762f328",
            "sourceColumn": "service",
            "summarizeBy": "none"
          },
          {
            "name": "Listed role",
            "dataType": "string",
            "lineageTag": "c723b154-15de-4959-bb2e-78dd3ddc7da3",
            "sourceColumn": "role",
            "summarizeBy": "none"
          },
          {
            "name": "Website",
            "dataType": "string",
            "lineageTag": "7af685eb-a48e-4b4e-b13f-c4468e71800b",
            "sourceColumn": "website",
            "summarizeBy": "none"
          },
          {
            "name": "iso3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5eddb3fc-f8d7-4903-95d2-f73f10c73aa3",
            "sourceColumn": "iso3",
            "summarizeBy": "none"
          },
          {
            "name": "source_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82d6e427-ae40-48a7-aa59-c17551b66cf7",
            "sourceColumn": "source_name",
            "summarizeBy": "none"
          },
          {
            "name": "review_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36f212b3-5d79-4f09-8453-1666d0b47687",
            "sourceColumn": "review_url",
            "summarizeBy": "none"
          },
          {
            "name": "screenshot_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccf53195-facd-4470-9760-807803f005bf",
            "sourceColumn": "screenshot_url",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "21ce899a-b70c-4cfa-9024-15022acf4086",
        "measures": [
          {
            "name": "Market count",
            "expression": "DISTINCTCOUNT(Listings[Market ID])",
            "formatString": "#,0",
            "lineageTag": "8010ccbf-eb22-4424-93c3-4e1bfbb23ff9"
          },
          {
            "name": "Service count",
            "expression": "DISTINCTCOUNT(Listings[Service ID])",
            "formatString": "#,0",
            "lineageTag": "5612e175-d313-4bf7-9b92-c089a1dea376"
          },
          {
            "name": "Listing count",
            "expression": "COUNTROWS(Listings)",
            "formatString": "#,0",
            "lineageTag": "d0951a2b-097c-439b-96ed-09506c678601"
          },
          {
            "name": "Primary listings",
            "expression": "COALESCE(CALCULATE(COUNTROWS(Listings), KEEPFILTERS(Listings[Listed role] = \"Primary\")), 0)",
            "formatString": "#,0",
            "lineageTag": "7b4d67fb-aea0-4d45-af53-f605b7f8c9e5"
          },
          {
            "name": "Markets listed",
            "expression": "DISTINCTCOUNT(Listings[Market ID])",
            "formatString": "#,0",
            "lineageTag": "1e9d4795-addb-43a0-aaa0-f631020d1b57"
          },
          {
            "name": "Top service coverage",
            "expression": "IF(RANKX(ALLSELECTED(Services), [Markets listed], , DESC, Skip) <= 12, [Markets listed])",
            "formatString": "#,0",
            "lineageTag": "a8d396e7-0811-4b29-a1bb-fd64f45a9043"
          },
          {
            "name": "Unverified shares",
            "expression": "COUNTROWS(FILTER(Markets, Markets[Share status] = \"Unverified\"))",
            "formatString": "#,0",
            "lineageTag": "7d90c159-f718-4bb0-a25d-c0d2da6cc781"
          },
          {
            "name": "Name corrections",
            "expression": "COUNTROWS(FILTER(Changes, Changes[Field] IN {\"App Name\", \"Alternate1 Name\", \"Alternate2 Name\"}))",
            "formatString": "#,0",
            "lineageTag": "ee5603e8-a6ee-4cc1-ba89-0f84ae191ba0"
          },
          {
            "name": "URL format changes",
            "expression": "COUNTROWS(FILTER(Changes, NOT(Changes[Field] IN {\"App Name\", \"Alternate1 Name\", \"Alternate2 Name\"})))",
            "formatString": "#,0",
            "lineageTag": "8db1d2fc-53ef-4935-8785-361c82084d7f"
          }
        ],
        "partitions": [
          {
            "name": "Listings",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Text.ToBinary(\"listing_id,market_id,country,iso3,service_id,service,source_name,role,website,review_url,screenshot_url#(lf)M001-1,M001,United States,USA,S9bb3a91fbff8,Apple Pay,Apple Pay,Primary,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M001-2,M001,United States,USA,Scfe1ae6e7f3a,Google Pay,Google Pay,Alternative 1,https://pay.google.com,https://www.pcmag.com/reviews/google-pay,https://ibb.co/bK79xby#(lf)M001-3,M001,United States,USA,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M002-1,M002,China,CHN,Sd5b72847b212,Alipay,Alipay,Primary,https://alipay.com,https://www.rapyd.net/blog/what-is-alipay/,https://ibb.co/ysHqJN4#(lf)M002-2,M002,China,CHN,Sa39c6414ea1e,WeChat Pay,WeChat Pay,Alternative 1,https://weixin.qq.com,https://www.weareplanet.com/blog/wechat-pay,https://ibb.co/Qk6Z7mw#(lf)M002-3,M002,China,CHN,Sf926e95ae759,UnionPay,UnionPay,Alternative 2,https://unionpayintl.com,https://www.trustpilot.com/review/unionpayintl.com,https://ibb.co/s1VmBC7#(lf)M003-1,M003,Germany,DEU,Sab8a4f6bb84d,PayPal,PayPal,Primary,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M003-2,M003,Germany,DEU,Sa2e779358d0d,Klarna,Klarna,Alternative 1,https://klarna.com,https://www.trustpilot.com/review/klarna.com,https://ibb.co/0F1XnJ8#(lf)M003-3,M003,Germany,DEU,S02f195c0ad8e,Sofort,Sofort,Alternative 2,https://sofort.com,https://www.trustpilot.com/review/sofort.com,https://ibb.co/pWKHfvh#(lf)M004-1,M004,Japan,JPN,S4d54ee71b475,PayPay,PayPay,Primary,https://paypay.ne.jp,https://www.g2.com/products/paypay/reviews,https://ibb.co/v1Xgpvs#(lf)M004-2,M004,Japan,JPN,Se3a205bb818f,LINE Pay,LINE Pay,Alternative 1,https://pay.line.me,https://www.trustpilot.com/review/linepay.fun,https://ibb.co/hW2py4P#(lf)M004-3,M004,Japan,JPN,S943d2ae40a1e,Rakuten Pay,Rakuten Pay,Alternative 2,https://rakuten.com,https://www.trustpilot.com/review/www.rakuten.com,https://ibb.co/whfG4z9#(lf)M005-1,M005,India,IND,Seb46c4263e56,PhonePe,PhonePe,Primary,https://phonepe.com,https://www.trustpilot.com/review/phonepe.com,https://ibb.co/YfdMZjP#(lf)M005-2,M005,India,IND,Scfe1ae6e7f3a,Google Pay,Google Pay,Alternative 1,https://pay.google.com,https://www.pcmag.com/reviews/google-pay,https://ibb.co/bK79xby#(lf)M005-3,M005,India,IND,Sb2a940b2a2ea,Paytm,Paytm,Alternative 2,https://paytm.com,https://www.trustradius.com/products/paytm/reviews,https://ibb.co/rmv6qP7#(lf)M006-1,M006,United Kingdom,GBR,Sab8a4f6bb84d,PayPal,PayPal,Primary,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M006-2,M006,United Kingdom,GBR,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 1,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M006-3,M006,United Kingdom,GBR,Sdd53271a2e06,Revolut,Revolut,Alternative 2,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/w69Nf7j#(lf)M007-1,M007,France,FRA,S4fe05e7db04b,Paylib,Paylib,Primary,https://paylib.fr,https://www.capterra.in/software/209162/paylib,https://ibb.co/y5vd2g2#(lf)M007-2,M007,France,FRA,S5a28fa1fccb6,Lydia,Lydia,Alternative 1,https://lydia-app.com,https://www.trustpilot.com/review/sumeria.eu?page=8,https://ibb.co/ZmKrjsd#(lf)M007-3,M007,France,FRA,Scfe1ae6e7f3a,Google Pay,Google Pay,Alternative 2,https://pay.google.com,https://www.pcmag.com/reviews/google-pay,https://ibb.co/bK79xby#(lf)M008-1,M008,Italy,ITA,S4a84d0c48b14,Satispay,Satispay,Primary,https://satispay.com,https://www.capterra.com/p/180716/Satispay/,https://ibb.co/5TRdXzx#(lf)M008-2,M008,Italy,ITA,S24ef7ec7e764,Nexi,Nexi,Alternative 1,https://nexi.it,https://www.trustpilot.com/review/www.nexi.it,https://ibb.co/hfv5mB7#(lf)M008-3,M008,Italy,ITA,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M009-1,M009,Canada,CAN,Sbd194199fe09,Interac,Interac,Primary,https://interac.ca,https://ca.trustpilot.com/review/interac.ca,https://ibb.co/WHXg50m#(lf)M009-2,M009,Canada,CAN,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 1,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M009-3,M009,Canada,CAN,Scfe1ae6e7f3a,Google Pay,Google Pay,Alternative 2,https://pay.google.com,https://www.pcmag.com/reviews/google-pay,https://ibb.co/bK79xby#(lf)M010-1,M010,Brazil,BRA,S41b0635bb279,PIX,PIX,Primary,https://mercadopago.com.br,https://www.trustpilot.com/review/www.mercadopago.com.br,https://ibb.co/TKGxSkP#(lf)M010-2,M010,Brazil,BRA,Sfe640272446b,Mercado Pago,Mercado Pago,Alternative 1,https://mercadopago.com,https://www.capterra.com/p/250909/Mercado-Pago/reviews/,https://ibb.co/ngttbxg#(lf)M010-3,M010,Brazil,BRA,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M011-1,M011,Russia,RUS,Scc9155d76e81,Yandex.Money,Yandex.Money,Primary,https://yoomoney.ru,https://ghanasoccernet.com/in/payment-system-review/yandex-money-payment-system-review/,https://ibb.co/2WxV2yw#(lf)M011-2,M011,Russia,RUS,S78832fd1d06f,Qiwi,Qiwi,Alternative 1,https://qiwi.com,https://www.trustpilot.com/review/qiwi.com,https://ibb.co/yRs9fwW#(lf)M011-3,M011,Russia,RUS,S8e61bf5c793c,WebMoney,WebMoney,Alternative 2,https://webmoney.ru,https://www.trustfinance.com/companies/web-money,https://ibb.co/cr3KgLC#(lf)M012-1,M012,South Korea,KOR,Sc4987750ae1c,KakaoPay,KakaoPay,Primary,https://kakaopay.com,https://www.capterra.in/software/1016162/kakao-pay,https://ibb.co/Dpnnn08#(lf)M012-2,M012,South Korea,KOR,Scd248346b654,Samsung Pay,Samsung Pay,Alternative 1,https://samsung.com/samsung-pay,\"\"https://www.capterra.in/reviews/213917/samsung-pay#(#):~:text=The%20interface%20is%20good%2C%20simple,a%20great%20option%20to%20value.\"\",https://ibb.co/bW78MJm#(lf)M012-3,M012,South Korea,KOR,S7906b84d8f9d,Naver Pay,Naver Pay,Alternative 2,https://naver.com,https://www.koreatimes.co.kr/www/biz/2025/01/602_297251.html,https://ibb.co/ThR2wFH#(lf)M013-1,M013,Australia,AUS,S032a27679a37,Afterpay,Afterpay,Primary,https://afterpay.com,https://www.capterra.in/reviews/1012480/afterpay,https://ibb.co/2KR5YTV#(lf)M013-2,M013,Australia,AUS,S81b959cfba68,Zip Pay,Zip Pay,Alternative 1,https://zip.co,https://au.trustpilot.com/review/zippay.com.au,https://ibb.co/X43h4JL#(lf)M013-3,M013,Australia,AUS,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M014-1,M014,Spain,ESP,S09bf90a11ae3,Bizum,Bizum,Primary,https://bizum.es,https://ca.trustpilot.com/review/bizum.es,https://ibb.co/0qHwrxj#(lf)M014-2,M014,Spain,ESP,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M014-3,M014,Spain,ESP,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M015-1,M015,Mexico,MEX,Scd248346b654,Samsung Pay,Samsung Pay,Primary,https://samsung.com/samsung-pay,\"\"https://www.capterra.in/reviews/213917/samsung-pay#(#):~:text=The%20interface%20is%20good%2C%20simple,a%20great%20option%20to%20value.\"\",https://ibb.co/gWdX1YC#(lf)M015-2,M015,Mexico,MEX,Sfe640272446b,Mercado Pago,Mercado Pago,Alternative 1,https://mercadopago.com,https://www.capterra.com/p/250909/Mercado-Pago/reviews/,https://ibb.co/ngttbxg#(lf)M015-3,M015,Mexico,MEX,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M016-1,M016,Indonesia,IDN,S683e3175233e,OVO,OVO,Primary,https://ovo.id,https://ca.trustpilot.com/review/ovo.id,https://ibb.co/zFJkZrL#(lf)M016-2,M016,Indonesia,IDN,S177eb549798b,GoPay,GoPay,Alternative 1,https://gopay.co.id,https://apps.apple.com/my/app/gopay-transfer-pulsa-bills/id6446321594,https://ibb.co/Nm42Mtb#(lf)M016-3,M016,Indonesia,IDN,S39dd0861d128,DANA,DANA,Alternative 2,https://dana.id,https://slashdot.org/software/p/DANA/,https://ibb.co/tCp8Z6B#(lf)M017-1,M017,Turkey,TUR,S12ca66653f33,BKM Express,BKM Express,Primary,https://bkm.com.tr,https://www.appbrain.com/appstore/bkm-express/ios-657408050,https://ibb.co/26Q3h1Y#(lf)M017-2,M017,Turkey,TUR,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M017-3,M017,Turkey,TUR,Sc6f881bfe8f5,Ininal,Ininal,Alternative 2,https://ininal.com,https://www.trustpilot.com/review/www.ininal.com,https://ibb.co/dWMPfbM#(lf)M018-1,M018,Netherlands,NLD,Sf54ab403ca1c,iDEAL,iDEAL,Primary,https://ideal.nl,https://ca.trustpilot.com/review/in3.ideal.nl,https://ibb.co/0B8z79s#(lf)M018-2,M018,Netherlands,NLD,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M018-3,M018,Netherlands,NLD,S832c3b1ba488,SEPA,SEPA,Alternative 2,https://ecb.europa.eu,https://www.gtreview.com/magazine/nov-dec-2013/sepa-review-race-to-the-finish/,https://ibb.co/tM6npKg#(lf)M019-1,M019,Saudi Arabia,SAU,Sbc7ff7a28899,STC Pay,STC Pay,Primary,https://stcpay.com.sa,https://ca.trustpilot.com/review/www.stc.com.sa,https://ibb.co/vjv4gDg#(lf)M019-2,M019,Saudi Arabia,SAU,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 1,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M019-3,M019,Saudi Arabia,SAU,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M020-1,M020,Switzerland,CHE,S4b4db0817515,TWINT,TWINT,Primary,https://twint.ch,https://ca.trustpilot.com/review/www.twint.ch,https://ibb.co/Gvb7cJG#(lf)M020-2,M020,Switzerland,CHE,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M020-3,M020,Switzerland,CHE,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M021-1,M021,Poland,POL,S354add2d89a1,BLIK,BLIK,Primary,https://blik.com,https://ca.trustpilot.com/review/blik.com,https://ibb.co/KGVH9B2#(lf)M021-2,M021,Poland,POL,Sdd53271a2e06,Revolut,Revolut,Alternative 1,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/xXdgkv4#(lf)M021-3,M021,Poland,POL,S97aaa5725e62,PayU,PayU,Alternative 2,https://payu.com,\"\"https://www.capterra.in/reviews/201075/payu#(#):~:text=PayU%20has%20an%20overall%20rating,47%20user%20reviews%20on%20Capterra.\"\",https://ibb.co/mBSmSGs#(lf)M022-1,M022,Taiwan,TWN,Se3a205bb818f,LINE Pay,Line Pay,Primary,https://linepay.com,https://tw.forumosa.com/t/line-pay-and-other-mobile-phone-payment-options/171901,https://ibb.co/BZyQ4TW#(lf)M022-2,M022,Taiwan,TWN,Sb0c9e4b4309e,JkoPay,JkoPay,Alternative 1,https://jkopay.com,https://trustburn.com/reviews/jkopay-co-ltd,https://ibb.co/8DmdVKY#(lf)M022-3,M022,Taiwan,TWN,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M023-1,M023,Belgium,BEL,S84e7c82fea0f,Bancontact,Bancontact,Primary,https://bancontact.com,https://slashdot.org/software/p/Bancontact/,https://ibb.co/Pxpc0FR#(lf)M023-2,M023,Belgium,BEL,S658e993fb9d6,Payconiq,Payconiq,Alternative 1,https://payconiq.com,https://www.trustpilot.com/review/payconiq.com,https://ibb.co/9vqY4mZ#(lf)M023-3,M023,Belgium,BEL,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M024-1,M024,Sweden,SWE,S1e73623015d3,Swish,Swish,Primary,https://swish.nu,https://ca.trustpilot.com/review/swish.nu,https://ibb.co/BnNc8P1#(lf)M024-2,M024,Sweden,SWE,Sa2e779358d0d,Klarna,Klarna,Alternative 1,https://klarna.com,https://www.trustpilot.com/review/klarna.com,https://ibb.co/0F1XnJ8#(lf)M024-3,M024,Sweden,SWE,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M025-1,M025,Argentina,ARG,Sfe640272446b,Mercado Pago,Mercado Pago,Primary,https://mercadopago.com,https://ca.trustpilot.com/review/mercadopago.com,https://ibb.co/0MLsspC#(lf)M025-2,M025,Argentina,ARG,Sb4047e184273,Naranja X,Naranja X,Alternative 1,https://naranjax.com,https://naranja-x.es.aptoide.com/app,https://ibb.co/ZLTSrdD#(lf)M025-3,M025,Argentina,ARG,Sa76287c409c4,Ualá,Ualá,Alternative 2,https://uala.com,https://www.trustpilot.com/review/uala.com.ar,https://ibb.co/N7N5KkX#(lf)M026-1,M026,Ireland,IRL,Sdd53271a2e06,Revolut,Revolut,Primary,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/xXdgkv4#(lf)M026-2,M026,Ireland,IRL,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M026-3,M026,Ireland,IRL,Sb86ee665f29a,N26,N26,Alternative 2,https://n26.com,https://www.trustpilot.com/review/n26.com,https://ibb.co/MVLCwgs#(lf)M027-1,M027,United Arab Emirates,ARE,S9bb3a91fbff8,Apple Pay,Apple Pay,Primary,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M027-2,M027,United Arab Emirates,ARE,Scd248346b654,Samsung Pay,Samsung Pay,Alternative 1,https://samsung.com/samsung-pay,\"\"https://www.capterra.in/reviews/213917/samsung-pay#(#):~:text=The%20interface%20is%20good%2C%20simple,a%20great%20option%20to%20value.\"\",https://ibb.co/bW78MJm#(lf)M027-3,M027,United Arab Emirates,ARE,S22f85bf6fa63,Noon Pay,Noon Pay,Alternative 2,https://noon.com,https://au.trustpilot.com/review/noon.com?page=73,https://ibb.co/rdMbBRG#(lf)M028-1,M028,Singapore,SGP,S09996930be63,GrabPay,GrabPay,Primary,https://grab.com,https://ca.trustpilot.com/review/grab.com,https://ibb.co/q10Tf69#(lf)M028-2,M028,Singapore,SGP,S5c5af06729d3,PayNow,PayNow,Alternative 1,https://abs.org.sg/consumer-banking/pay-now,https://www.trustpilot.com/review/paynow-app.com,https://ibb.co/HFNHcw3#(lf)M028-3,M028,Singapore,SGP,Sc953363739d2,DBS PayLah,DBS PayLah,Alternative 2,https://dbs.com.sg,https://www.trustpilot.com/review/dbs.com?page=3,https://ibb.co/kq0fZ1P#(lf)M029-1,M029,Austria,AUT,Seecadce162c6,MobilePay,Mobile Pay,Primary,https://mobilepay.dk,https://www.g2.com/products/paypay/reviews,https://ibb.co/hc51xx8#(lf)M029-2,M029,Austria,AUT,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M029-3,M029,Austria,AUT,Sa2e779358d0d,Klarna,Klarna,Alternative 2,https://klarna.com,https://www.capterra.com/p/230509/Klarna/reviews/,https://ibb.co/Y75KJmC#(lf)M030-1,M030,Israel,ISR,S1c8aa3a6466b,Payoneer,Payoneer,Primary,https://payoneer.com,https://ca.trustpilot.com/review/www.payoneer.com,https://ibb.co/rf0gZn3#(lf)M030-2,M030,Israel,ISR,Se1acedc90190,BitPay,BitPay,Alternative 1,https://bitpay.com,https://www.trustpilot.com/review/bitpay.com?page=3,https://ibb.co/NSqLXtn#(lf)M030-3,M030,Israel,ISR,Sf2bcbe5abd94,Isracard,Isracard,Alternative 2,https://isracard.co.il,https://www.glassdoor.co.in/Reviews/Isracard-Reviews-E553776.htm,https://ibb.co/CBVNxxd#(lf)M031-1,M031,Thailand,THA,S67799a5cdcb4,Rabbit Line Pay,Rabbit Line Pay,Primary,https://rabbit.co.th,https://payatlas.com/company/rabbit-line-pay/729#(#)company-about,https://ibb.co/PWXrc8V#(lf)M031-2,M031,Thailand,THA,S06780a7a437a,TrueMoney,TrueMoney,Alternative 1,https://truemoney.com,https://play.google.com/store/apps/details?id=th.co.truemoney.wallet&hl=en-US,https://ibb.co/zJqzsYv#(lf)M031-3,M031,Thailand,THA,Sd5b72847b212,Alipay,Alipay,Alternative 2,https://alipay.com,https://www.rapyd.net/blog/what-is-alipay/,https://ibb.co/ysHqJN4#(lf)M032-1,M032,Philippines,PHL,Seffe340b87b3,GCash,GCash,Primary,https://gcash.com,https://ca.trustpilot.com/review/www.gcash.com,https://ibb.co/kJ86hWM#(lf)M032-2,M032,Philippines,PHL,Scc2cd9293700,PayMaya,PayMaya,Alternative 1,https://paymaya.com,https://www.trustpilot.com/review/paymaya.com,https://ibb.co/HrbVyr9#(lf)M032-3,M032,Philippines,PHL,S09996930be63,GrabPay,GrabPay,Alternative 2,https://grab.com,https://vulcanpost.com/666509/grabpay-review-e-wallet-singapore/,https://ibb.co/kHBvqQs#(lf)M033-1,M033,Vietnam,VNM,S4f61b35afbac,MoMo,MoMo,Primary,https://momo.vn,https://en.vietnamplus.vn/momo-remains-most-popular-e-wallet-in-vietnam-post279729.vnp,https://ibb.co/VLSS3ph#(lf)M033-2,M033,Vietnam,VNM,Sfb4a70e1beb4,ZaloPay,ZaloPay,Alternative 1,https://zalopay.vn,https://apps.apple.com/vn/app/zalopay-thanh-to%C3%A1n-t%C3%ADch-th%C6%B0%E1%BB%9Fng/id1112407590?see-all=reviews,https://ibb.co/xJR2WPG#(lf)M033-3,M033,Vietnam,VNM,S556d78f4690a,Viettel Pay,Viettel Pay,Alternative 2,https://viettelpay.vn,https://www.trustpilot.com/review/viettel.com.vn,https://ibb.co/mF7W04Y#(lf)M034-1,M034,Norway,NOR,S8c98ead1dc6f,Vipps,Vipps,Primary,https://vipps.no,https://ca.trustpilot.com/review/vipps.no,https://ibb.co/f0kgQJ4#(lf)M034-2,M034,Norway,NOR,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M034-3,M034,Norway,NOR,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M035-1,M035,Malaysia,MYS,Sda053fa8064d,Touch 'n Go,Touch 'n Go,Primary,https://touchngo.com.my,https://ca.trustpilot.com/review/www.touchngo.com.my,https://ibb.co/C9m3MGY#(lf)M035-2,M035,Malaysia,MYS,S2d0bec069274,CIMB OCTO MY,CIMB OCTO MY,Alternative 1,https://cimb.com.my,https://appshunter.io/ios/app/1591184221,https://ibb.co/DMn8vH8#(lf)M035-3,M035,Malaysia,MYS,S0d791a0a6f01,Boost,Boost,Alternative 2,https://myboost.co/,https://ie.trustpilot.com/review/www.boostmobile.com?page=27,https://ibb.co/jrvzjy3#(lf)M036-1,M036,Iran,IRN,S1bd7750deb16,Shetab,Shetab,Primary,https://shetab.com,https://360techblogs.blogspot.com/2025/01/review-of-shetabcom-detailed-look-at.html,https://ibb.co/6812V6T#(lf)M036-2,M036,Iran,IRN,S4497ba648fd9,Zarinpal,Zarinpal,Alternative 1,https://zarinpal.com,https://www.glassdoor.co.in/Reviews/ZarinPal-Reviews-E4994915.htm,https://ibb.co/zRpMc5f#(lf)M036-3,M036,Iran,IRN,Sd2cb4f99541e,Pay.ir,Pay.ir,Alternative 2,https://pay.ir,https://360techblogs.blogspot.com/2025/01/review-of-payir-comprehensive-overview.html,https://ibb.co/ZRj0tYd#(lf)M037-1,M037,Bangladesh,BGD,S5dbff7563966,bKash,bKash,Primary,https://bkash.com,https://ca.trustpilot.com/review/www.bkash.com,https://ibb.co/x1QBytF#(lf)M037-2,M037,Bangladesh,BGD,S1eb67b986588,Nagad,Nagad,Alternative 1,https://nagad.com.bd,https://www.trustpilot.com/review/nagad.com.bd,https://ibb.co/HgbpYb0#(lf)M037-3,M037,Bangladesh,BGD,Sd40a5aca994e,Rocket,Rocket,Alternative 2,https://dutchbanglabank.com,https://ie.trustpilot.com/review/dutchbanglabank.com,https://ibb.co/RPR29dS#(lf)M038-1,M038,Denmark,DNK,Seecadce162c6,MobilePay,MobilePay,Primary,https://mobilepay.dk,https://ca.trustpilot.com/review/mobilepay.dk,https://ibb.co/hc51xx8#(lf)M038-2,M038,Denmark,DNK,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 1,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M038-3,M038,Denmark,DNK,Scfe1ae6e7f3a,Google Pay,Goggle Pay,Alternative 2,https://pay.google.com,https://www.pcmag.com/reviews/google-pay,https://ibb.co/bK79xby#(lf)M039-1,M039,Hong Kong,HKG,Sd5b72847b212,Alipay,Alipay,Primary,https://alipay.com,https://www.rapyd.net/blog/what-is-alipay/,https://ibb.co/ysHqJN4#(lf)M039-2,M039,Hong Kong,HKG,Sa39c6414ea1e,WeChat Pay,WeChat Pay,Alternative 1,https://weixin.qq.com,https://www.weareplanet.com/blog/wechat-pay,https://ibb.co/Qk6Z7mw#(lf)M039-3,M039,Hong Kong,HKG,Sa7c7b3a28a61,Octopus,Octopus,Alternative 2,https://octopus.com.hk,https://www.reddit.com/r/HongKong/comments/18u82k4/i_love_octopus_cards/,https://ibb.co/LS8BSkZ#(lf)M040-1,M040,Colombia,COL,Sb059c7cc919f,Nequi,Nequi,Primary,https://nequi.com.co,https://ca.trustpilot.com/review/www.nequi.com.co,https://ibb.co/j4zmMP9#(lf)M040-2,M040,Colombia,COL,S49b7ccf946a7,Daviplata,Daviplata,Alternative 1,https://daviplata.com,https://play.google.com/store/apps/details?id=com.davivienda.daviplataapp&hl=en-US,https://ibb.co/5vjfFYb#(lf)M040-3,M040,Colombia,COL,S8370f96e9d93,Bancolombia,Bancolombia,Alternative 2,https://bancolombia.com,https://www.trustpilot.com/review/www.bancolombia.com,https://ibb.co/Fm4KC2P#(lf)M041-1,M041,South Africa,ZAF,S712542eb0998,SnapScan,SnapScan,Primary,https://snapscan.co.za,https://www.hellopeter.com/snapscan,https://ibb.co/KX04HQm#(lf)M041-2,M041,South Africa,ZAF,S088cc9c6f49b,Zapper,Zapper,Alternative 1,https://zapper.com,https://www.hellopeter.com/zapper,https://ibb.co/ChdBfRK#(lf)M041-3,M041,South Africa,ZAF,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M042-1,M042,Romania,ROU,Seecadce162c6,MobilePay,MobilePay,Primary,https://mobilepay.dk,https://ca.trustpilot.com/review/mobilepay.dk,https://ibb.co/hc51xx8#(lf)M042-2,M042,Romania,ROU,S97aaa5725e62,PayU,PayU,Alternative 1,https://payu.com,https://www.g2.com/products/payu/reviews#(#)reviews,https://ibb.co/Q8YT8gD#(lf)M042-3,M042,Romania,ROU,Sdd53271a2e06,Revolut,Revolut,Alternative 2,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/w69Nf7j#(lf)M043-1,M043,Egypt,EGY,Se9bcb76e743e,Fawry,Fawry,Primary,https://fawry.com,https://justuseapp.com/en/app/1462911630/myfawry/reviews,https://ibb.co/tHCRByZ#(lf)M043-2,M043,Egypt,EGY,Sf63ecf4435b0,myfawry,myfawry,Alternative 1,https://fawry.com,https://appshunter.io/ios/app/1462911630,https://ibb.co/806vTRx#(lf)M043-3,M043,Egypt,EGY,See286ba33708,Aman,Aman,Alternative 2,https://aman.eg,https://support.paytabs.com/en/support/solutions/articles/60000818129-aman-activation-and-workflow-user-experience,https://ibb.co/8zvqCxg#(lf)M044-1,M044,Pakistan,PAK,Sa0b41fabd1f4,JazzCash,JazzCash,Primary,https://jazzcash.com.pk,https://ca.trustpilot.com/review/jazzcash.com.pk,https://ibb.co/Qb0sCXK#(lf)M044-2,M044,Pakistan,PAK,S8a2d4c009231,EasyPaisa,EasyPaisa,Alternative 1,https://easypaisa.com.pk,https://www.trustpilot.com/review/easypaisa.com,https://ibb.co/VJX6vSz#(lf)M044-3,M044,Pakistan,PAK,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M045-1,M045,Chile,CHL,S722f7eba24a7,WebPay,WebPay,Primary,https://webpay.cl,https://saasguro.com/products/webpay,https://ibb.co/HPRXSJf#(lf)M045-2,M045,Chile,CHL,Se2d8004648db,Transbank,Transbank,Alternative 1,https://transbank.cl,https://appshunter.io/ios/app/1432114499,https://ibb.co/4tDfP5z#(lf)M045-3,M045,Chile,CHL,S888804c60126,Khipu,Khipu,Alternative 2,https://khipu.com,https://www.nuvei.com/apm/khipu,https://ibb.co/JCKtYhw#(lf)M046-1,M046,Czech Republic,CZE,S177eb549798b,GoPay,GoPay,Primary,https://gopay.co.id,https://duwitmu.com/tabungan/gopay-aplikasi-review-jujur-cara-daftar-top-up,https://ibb.co/BZ7dZNg#(lf)M046-2,M046,Czech Republic,CZE,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M046-3,M046,Czech Republic,CZE,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M047-1,M047,Finland,FIN,Seecadce162c6,MobilePay,MobilePay,Primary,https://mobilepay.dk,https://ca.trustpilot.com/review/mobilepay.dk,https://ibb.co/hc51xx8#(lf)M047-2,M047,Finland,FIN,S3e68d4365d41,Siirto,Siirto,Alternative 1,https://siirto.fi,https://appshunter.io/ios/app/1156811861,https://ibb.co/fqqfL9m#(lf)M047-3,M047,Finland,FIN,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M048-1,M048,Portugal,PRT,Sa70a35b72c22,MB Way,MB Way,Primary,https://mbway.pt,https://justuseapp.com/en/app/918126133/mb-way/reviews,https://ibb.co/dGMZHCV#(lf)M048-2,M048,Portugal,PRT,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M048-3,M048,Portugal,PRT,Sdd53271a2e06,Revolut,Revolut,Alternative 2,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/w69Nf7j#(lf)M049-1,M049,Hungary,HUN,S19ce229ca0ea,SimplePay,SimplePay,Primary,https://simplepay.com,https://www.scam-detector.com/validator/simplepay-hu-review/,https://ibb.co/ZJX3Z5C#(lf)M049-2,M049,Hungary,HUN,S9f4c0a6f6150,Barion,Barion,Alternative 1,https://barion.com,https://appshunter.io/ios/app/896714923,https://ibb.co/VCKH0Q3#(lf)M049-3,M049,Hungary,HUN,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M050-1,M050,Kazakhstan,KAZ,S355387169087,Kaspi.kz,Kaspi.kz,Primary,https://kaspi.kz,https://ca.trustpilot.com/review/kaspi.kz,https://ibb.co/Kb1LWk0#(lf)M050-2,M050,Kazakhstan,KAZ,S88853e062e22,Halyk Bank,Halyk Bank,Alternative 1,https://halykbank.kz,https://appshunter.io/ios/app/1496747464,https://ibb.co/ChMkvtk#(lf)M050-3,M050,Kazakhstan,KAZ,S1b96cf56a09b,Paybox,Paybox,Alternative 2,https://paybox.ru,https://www.crunchbase.com/organization/paybox-money,https://ibb.co/9vdfpwR#(lf)M051-1,M051,Peru,PER,S560f89b4e57b,Yape,Yape,Primary,https://yape.com.pe,https://www.appbrain.com/app/yape/com.bcp.innovacxion.yapeapp,https://ibb.co/8mfYBFK#(lf)M051-2,M051,Peru,PER,S5e1d15a80a51,Banca Móvil BCP,Banca Móvil BCP,Alternative 1,https://www.pichincha.com/banca-movil,https://appshunter.io/ios/app/777961079,https://ibb.co/ww6stk3#(lf)M051-3,M051,Peru,PER,S0f07802df56d,Niubiz,Niubiz,Alternative 2,https://niubiz.com.pe,https://www.scam-detector.com/validator/niubiz-com-review/,https://ibb.co/wWj5LRB#(lf)M052-1,M052,Iraq,IRQ,Sfb1c3e32ff7c,Zain Cash,Zain Cash,Primary,https://zaincash.iq,https://www.appbrain.com/app/zaincash-%D8%B2%D9%8A%D9%86-%D9%83%D8%A7%D8%B4/mobi.foo.zaincash,https://ibb.co/71CFmPF#(lf)M052-2,M052,Iraq,IRQ,S87bb80aa218c,Qi Services,Qi Services,Alternative 1,https://qi.iq/en/digital-zone,https://qi-services.en.softonic.com/android,https://ibb.co/93j3qFM#(lf)M052-3,M052,Iraq,IRQ,S33e6460b0614,FastPay,FastPay,Alternative 2,https://fast-pay.iq,https://www.trustpilot.com/review/fast-pay.cash,https://ibb.co/FBzJMyS#(lf)M053-1,M053,Greece,GRC,Seff765f55a78,Viva Wallet,Viva Wallet,Primary,https://vivawallet.com,https://ca.trustpilot.com/review/viva.com,https://ibb.co/GJykLVm#(lf)M053-2,M053,Greece,GRC,Sab8a4f6bb84d,PayPal,Paypal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M053-3,M053,Greece,GRC,Sdd53271a2e06,Revolut,Revolut,Alternative 2,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/w69Nf7j#(lf)M054-1,M054,Algeria,DZA,S3bf830ec58e4,Barid Bank,Barid Bank,Primary,https://albaridbank.ma/fr/nos-solutions/barid-bank-mobile,https://justuseapp.com/en/app/720775151/barid-bank-mobile/reviews#(#)google_vignette,https://ibb.co/j6c78Hq#(lf)M054-2,M054,Algeria,DZA,Sa9314df8e7a9,CIB,CIB,Alternative 1,https://cibeg.com,https://play.google.com/store/apps/details/CIB_Mobile_Banking_App?id=com.cibeg.ddc1.digitalbanking.live&hl=en-US,https://ibb.co/d6RkPPC#(lf)M054-3,M054,Algeria,DZA,Sb776149d47e3,CashAddress,CashAddress,Alternative 2,https://cashaddress.org,https://www.reddit.com/r/btc/comments/9x1mkh/another_scam_wallet_cashaddress_paper_wallet/?rdt=51494,https://ibb.co/93hdjsH#(lf)M055-1,M055,New Zealand,NZL,S9bb3a91fbff8,Apple Pay,Apple Pay,Primary,https://apple.com/apple-pay,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M055-2,M055,New Zealand,NZL,S032a27679a37,Afterpay,Afterpay,Alternative 1,https://afterpay.com,https://appshunter.io/ios/app/1401019110,https://ibb.co/hW7by4s#(lf)M055-3,M055,New Zealand,NZL,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M056-1,M056,Qatar,QAT,S6de18e00d6b3,Ooredoo Money,Ooredoo Money,Primary,https://ooredoo.qa/web/en/ooredoo-money/,https://download.cnet.com/ooredoo-money/3000-2057_4-77112319.html,https://ibb.co/F8JL2YR#(lf)M056-2,M056,Qatar,QAT,Sf1624fcc63b6,Binance,Binance,Alternative 1,https://binance.com,https://www.hedgewithcrypto.com/binance-review/,https://ibb.co/gjnVjnP#(lf)M056-3,M056,Qatar,QAT,S0dbf7f12f197,CBQ Mobile,CBQ Mobile,Alternative 2,https://cbq.qa,https://appshunter.io/ios/app/388934616,https://ibb.co/Drn1xm1#(lf)M057-1,M057,Ethiopia,ETH,S721a27a1aa5e,M-Birr,M-Birr,Primary,https://m-birr.com,https://www.eib.org/en/publications/interactive/the-eib-outside-the-eu-2017/m-birr-realising-the-potential-of-mobile-payments/,https://ibb.co/JmC0w03#(lf)M057-2,M057,Ethiopia,ETH,S1c8aa3a6466b,Payoneer,Payoneer,Alternative 1,https://payoneer.com,https://ca.trustpilot.com/review/www.payoneer.com,https://ibb.co/yWDKwwj#(lf)M057-3,M057,Ethiopia,ETH,Sfc8e27f609f4,Amole,Amole,Alternative 2,https://dashenbanksc.com/amole-payment-services/,https://play.google.com/store/apps/details?id=com.cr2.dashenamole&hl=en_IN,https://ibb.co/V2BB8p4#(lf)M058-1,M058,Nigeria,NGA,S8421e6a3d5ee,Paystack,Paystack,Primary,https://paystack.com,https://ca.trustpilot.com/review/paystack.com,https://ibb.co/YXP2STN#(lf)M058-2,M058,Nigeria,NGA,S419c017fec88,Flutterwave,Flutterwave,Alternative 1,https://flutterwave.com,https://appshunter.io/ios/app/1534897339,https://ibb.co/f0hSmtw#(lf)M058-3,M058,Nigeria,NGA,Sf465788dea89,Moniepoint,Moniepoint,Alternative 2,https://moniepoint.com,https://www.trustpilot.com/review/moniepoint.com,https://ibb.co/C24mNdy#(lf)M059-1,M059,Ukraine,UKR,Safbffd978275,PrivatBank,PrivatBank,Primary,https://privatbank.ua,https://ca.trustpilot.com/review/privatbank.ua,https://ibb.co/tq8wXpM#(lf)M059-2,M059,Ukraine,UKR,S9722e8c42d66,Monobank,Monobank,Alternative 1,https://monobank.ua,https://appshunter.io/ios/app/1287005205,https://ibb.co/pvgRWj3#(lf)M059-3,M059,Ukraine,UKR,S84287a10e6fb,PUMB,PUMB,Alternative 2,https://pumb.ua,https://www.trustpilot.com/review/pumb.ua,https://ibb.co/KsJsXZt#(lf)M060-1,M060,Morocco,MAR,S6f21be3f4238,Wafacash,Wafacash,Primary,https://wafacash.com,https://appshunter.io/ios/app/1505080908,https://ibb.co/9w0v9RS#(lf)M060-2,M060,Morocco,MAR,Sb3b4252796e8,CIH Mobile,CIH Mobile,Alternative 1,https://cihbank.ma,https://appshunter.io/ios/app/664637221,https://ibb.co/wZnNg5C#(lf)M060-3,M060,Morocco,MAR,Sa35b4fd24390,Cash Plus,Cash Plus,Alternative 2,https://cashplus.ma,https://www.trustpilot.com/review/cashplus.ma,https://ibb.co/1dKy8n3#(lf)M061-1,M061,Kuwait,KWT,Sc43969a3bafd,KNET,KNET,Primary,https://knet.com.kw,https://support.tap.company/en/support/solutions/articles/153000140240-what-is-knet-how-can-i-accept-knet-on-my-website-or-mobile-app-,https://ibb.co/JqNnP70#(lf)M061-2,M061,Kuwait,KWT,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M061-3,M061,Kuwait,KWT,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M062-1,M062,Cuba,CUB,Sb1b70335837f,Transfermóvil,Transfermóvil,Primary,https://etecsa.cu/en/entrepreneurs/transfermovil,https://transfermovil.en.softonic.com/android,https://website not accessable#(lf)M062-2,M062,Cuba,CUB,Sdc19504a356a,EnZona,EnZona,Alternative 1,https://www.enzona.net,https://www.xetid.cu/en/productos/enzona,https://ibb.co/L9xMkt4#(lf)M062-3,M062,Cuba,CUB,S716188579105,Moneda U,Moneda U,Alternative 2,https://somosmoneda.app,https://360techblogs.blogspot.com/2025/01/review-of-somos-moneda-your-trusted.html,https://ibb.co/hH2GtgF#(lf)M063-1,M063,Slovakia,SVK,Sdc665e6c8a2c,VIAMO,VIAMO,Primary,https://viamo.io,https://appshunter.io/ios/app/644270145,https://ibb.co/Fq9t0rp#(lf)M063-2,M063,Slovakia,SVK,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M063-3,M063,Slovakia,SVK,S9bb3a91fbff8,Apple Pay,Apple Pay,Alternative 2,https://apple.com/apple-pay/,https://www.pcmag.com/reviews/apple-pay,https://ibb.co/gTyz7dQ#(lf)M064-1,M064,Dominican Republic,DOM,S30438e444cb9,Orange Money,Orange Money,Primary,https://orange.com,https://africanreview.com/finance/banking-a-finance/orange-money-fintech-is-proving-a-game-changer-in-africa,https://ibb.co/0MptPcg#(lf)M064-2,M064,Dominican Republic,DOM,S2f77e8e6b5c1,Billet,Billet,Alternative 1,https://billet.do/,https://play.google.com/store/apps/details?id=com.billet.mpos&hl=en-US,https://ibb.co/h2qNZS8#(lf)M064-3,M064,Dominican Republic,DOM,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M065-1,M065,Uzbekistan,UZB,S95ba4ed9329f,Click,Click,Primary,https://click.uz,https://ca.trustpilot.com/review/click.uz,https://ibb.co/qknvps8#(lf)M065-2,M065,Uzbekistan,UZB,Sf06f0269cf5d,Payme,Payme,Alternative 1,https://payme.uz,https://play.google.com/store/apps/details?id=uz.dida.payme&hl=ru,https://ibb.co/QmLNCR3#(lf)M065-3,M065,Uzbekistan,UZB,S6e23756c3c9b,UzCard,UzCard,Alternative 2,https://uzcard.uz,https://360techblogs.blogspot.com/2025/01/review-of-uzcard-naked-new-standard-in.html,https://ibb.co/k9p7NDP#(lf)M066-1,M066,Bulgaria,BGR,S4d8fcc240109,ePay,ePay,Primary,https://epay.com,https://ca.trustpilot.com/review/epay.com,https://ibb.co/6084mxk#(lf)M066-2,M066,Bulgaria,BGR,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M066-3,M066,Bulgaria,BGR,Sf9b71269f6ff,EasyPay,EasyPay,Alternative 2,https://easypay.ua,https://www.trustpilot.com/review/easypay.pt,https://ibb.co/02fC6Nk#(lf)M067-1,M067,Ecuador,ECU,S8bb8de8cc73e,Kushki,Kushki,Primary,https://kushkipagos.com,https://www.expreso.ec/ciencia-y-tecnologia/kushki-plataforma-local-pagos-digitales-replica-6-paises-5504.html,https://ibb.co/KzzgCrB#(lf)M067-2,M067,Ecuador,ECU,S1b57eeacfbd3,PICHINCHA BANCA,PICHINCHA BANCA,Alternative 1,https://pichincha.com,https://www.appbrain.com/app/pichincha-banca-m%C3%B3vil/com.yellowpepper.pichincha,https://ibb.co/z2TBscP#(lf)M067-3,M067,Ecuador,ECU,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M068-1,M068,Puerto Rico,PRI,Sa186ae7a8096,ATH Móvil,ATH Móvil,Primary,https://athmovil.com,https://ath-movil.en.softonic.com/android,https://website not accessable#(lf)M068-2,M068,Puerto Rico,PRI,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M068-3,M068,Puerto Rico,PRI,Sa1593ecc5a13,Venmo,Venmo,Alternative 2,https://venmo.com,https://www.getapp.com/website-ecommerce-software/a/venmo/reviews/,https://ibb.co/p4QBD9s#(lf)M069-1,M069,Kenya,KEN,S53db2806be5a,M-Pesa,M-Pesa,Primary,https://mpesa.com,https://tech-ish.com/2021/02/01/new-m-pesa-app-really-good/,https://ibb.co/85ZHXB9#(lf)M069-2,M069,Kenya,KEN,Sf2f6a0188995,Loop,Loop,Alternative 1,https://loop.co.ke,https://loop-discover-pay-grow.en.softonic.com/android,https://ibb.co/DVXhn9P#(lf)M069-3,M069,Kenya,KEN,Sb1a34ffcbfc3,T-Kash,T-Kash,Alternative 2,https://telkom.co.ke/,https://apps.apple.com/ke/app/t-kash/id1569568640,https://ibb.co/KFnPxXW#(lf)M070-1,M070,Angola,AGO,S94f173f4b39c,ZAP,ZAP,Primary,https://zap.com,https://www.menosfios.com/en/a-evolucao-do-zap-on-uma-nova-experiencia-para-o-utilizador-de-telecomunicacoes-em-angola/,https://ibb.co/7v9F0JL#(lf)M070-2,M070,Angola,AGO,Sf46b7c2274d4,Easypay,Easypay,Alternative 1,https://easypay.com,https://www.trustpilot.com/review/easypay.pt,https://ibb.co/02fC6Nk#(lf)M070-3,M070,Angola,AGO,Seffe340b87b3,GCash,GCash,Alternative 2,https://gcash.com,https://ca.trustpilot.com/review/www.gcash.com,https://ibb.co/Sy6q9yQ#(lf)M071-1,M071,Guatemala,GTM,Seffe340b87b3,GCash,GCash,Primary,https://gcash.com,https://ca.trustpilot.com/review/www.gcash.com,https://ibb.co/S0S4qSG#(lf)M071-2,M071,Guatemala,GTM,S9ab007d4bdcf,BANRURAL,BANRURAL,Alternative 1,https://banrural.com.gt,https://appshunter.io/ios/app/6502616200,https://ibb.co/ypKY07C#(lf)M071-3,M071,Guatemala,GTM,S42fa0795c14e,MiDinero,MiDinero,Alternative 2,https://midinero.com.uy,https://es.trustpilot.com/review/www.midinero.com.uy,https://ibb.co/smfwBgb#(lf)M072-1,M072,Oman,OMN,S9b425f30fe38,Oman Mobile Payment,Oman Mobile Payment,Primary,https://omantel.om,https://www.appbrain.com/app/omantel/com.omantel,https://ibb.co/3kCtZr7#(lf)M072-2,M072,Oman,OMN,Sd274d9c0228d,PayCash,PayCash,Alternative 1,https://paycash.com,https://www.scam-detector.com/validator/paycash-app-review/,https://ibb.co/1bDBgdY#(lf)M072-3,M072,Oman,OMN,S9fdb2b0725ab,Bank Muscat,Bank Muscat ,Alternative 2,https://bankmuscat.com,https://www.trustpilot.com/review/www.bankmuscat.com,https://ibb.co/6ZgDRJd#(lf)M073-1,M073,Venezuela,VEN,S9656243ca723,Movilnet,Movilnet,Primary,https://movilnet.net,https://www.appbrain.com/app/movilnet/com.movilnet.movilnet_mobile_app,https://ibb.co/1XRhQCP#(lf)M073-2,M073,Venezuela,VEN,S028fa62fc793,Banco de Venezuela,Banco de Venezuela,Alternative 1,https://bancodevenezuela.com,https://apps.apple.com/ve/app/bdvapp/id1629896484?l=en-GB,https://ibb.co/b7HZ0gn#(lf)M073-3,M073,Venezuela,VEN,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M074-1,M074,Costa Rica,CRI,S5a33d5fbfbc5,bank BCR,bank BCR,Primary,https://bcr.ro,https://ca.trustpilot.com/review/www.bcr.ro,https://ibb.co/f4GzRtQ#(lf)M074-2,M074,Costa Rica,CRI,S847ed24aba8f,BAC Credomatic,BAC Credomatic,Alternative 1,https://baccredomatic.com,https://apps.apple.com/in/app/banca-m%C3%B3vil-bac/id465508552,https://ibb.co/TbJy5st#(lf)M074-3,M074,Costa Rica,CRI,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M075-1,M075,Luxembourg,LUX,S658e993fb9d6,Payconiq,Payconiq,Primary,https://payconiq.com,https://www.trustpilot.com/review/payconiq.com,https://ibb.co/qjhFN2Z#(lf)M075-2,M075,Luxembourg,LUX,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M075-3,M075,Luxembourg,LUX,S4b4db0817515,TWINT,Twint,Alternative 2,https://twint.ch,https://www.trustpilot.com/review/www.twint.ch,https://ibb.co/J3kwbSY#(lf)M076-1,M076,Croatia,HRV,S8409bece1699,AirCash,AirCash,Primary,https://aircash.eu,https://www.trustpilot.com/review/www.aircash.eu,https://ibb.co/dg5XgfR#(lf)M076-2,M076,Croatia,HRV,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M076-3,M076,Croatia,HRV,Saaabb660e287,Vertex,Vertex,Alternative 2,https://vertexinc.com,https://www.trustpilot.com/review/vertexinc.com,https://ibb.co/tHnzMvn#(lf)M077-1,M077,Panama,PAN,S2a2a83212153,Yappy,Yappy,Primary,https://www.yappy.com.pa,https://yappy.en.softonic.com/android,https://ibb.co/QYksyTm#(lf)M077-2,M077,Panama,PAN,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M077-3,M077,Panama,PAN,S6091bb1c77f0,Banistmo,Banistmo,Alternative 2,https://banistmo.com,https://play.google.com/store/apps/details/Banistmo_APP_Personas?id=com.banistmo.transaccional.personas&hl=en_IN,https://ibb.co/bKG0xdn#(lf)M078-1,M078,Ivory Coast,CIV,S30438e444cb9,Orange Money,Orange Money,Primary,https://orange.com,https://africanreview.com/finance/banking-a-finance/orange-money-fintech-is-proving-a-game-changer-in-africa,https://ibb.co/0MptPcg#(lf)M078-2,M078,Ivory Coast,CIV,S57b68256e28f,MTN Mobile Money,MTN Mobile Money,Alternative 1,https://momo.mtn.com,https://pctechmag.com/2020/05/mtn-momo-app-review/,https://ibb.co/j6sQVjD#(lf)M078-3,M078,Ivory Coast,CIV,S4f61b35afbac,MoMo,MoMo,Alternative 2,https://momo.vn,https://vir.com.vn/momo-dominates-vietnams-e-wallet-market-with-68-per-cent-share-102059.html,https://ibb.co/RBkdJwB#(lf)M079-1,M079,Sri Lanka,LKA,Sd289ae1c3730,Dialog eZ Cash,Dialog eZ Cash,Primary,https://dialog.lk,https://www.trustpilot.com/review/dialog.lk,https://ibb.co/zHT57Nv#(lf)M079-2,M079,Sri Lanka,LKA,S4dc53e64465b,Sampath e-Wallet,Sampath e-Wallet,Alternative 1,https://sampath.lk,https://sampath bank mobile app apk for android - download,https://ibb.co/wcGB4T8#(lf)M079-3,M079,Sri Lanka,LKA,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M080-1,M080,Turkmenistan,TKM,S813979cbe3f6,Çapar Pay,Çapar Pay,Primary,https://post.tm/,https://capar-toelegler-we-biletler.en.softonic.com/android,https://ibb.co/ct3wx3W#(lf)M080-2,M080,Turkmenistan,TKM,Sfe4df7a72733,Galkan töleg,Galkan töleg,Alternative 1,https://asuda.gov.tm,https://play.google.com/store/apps/details?id=mia.gov.tm&hl=en_IN,https://ibb.co/t8w9zDs#(lf)M080-3,M080,Turkmenistan,TKM,S99aa3e6c42cc,e gov tm,e gov tm,Alternative 2,https://e.gov.tm,https://e-gov-tm.en.softonic.com/android,https://ibb.co/n3n50XC#(lf)M081-1,M081,Lithuania,LTU,Sfd6f7a606c5b,Paysera,Paysera,Primary,https://paysera.com,https://www.trustpilot.com/review/www.paysera.com,https://ibb.co/StD1BCq#(lf)M081-2,M081,Lithuania,LTU,Sdd53271a2e06,Revolut,Revolut,Alternative 1,https://revolut.com,https://www.trustpilot.com/review/www.revolut.com,https://ibb.co/w69Nf7j#(lf)M081-3,M081,Lithuania,LTU,S0e8f6fd2e105,TransferGo,TransferGo,Alternative 2,https://transfergo.com,https://www.trustpilot.com/review/transfergo.com,https://ibb.co/8XwW6MZ#(lf)M082-1,M082,Uruguay,URY,S1f12994d9b0c,dLocal,dLocal,Primary,https://dlocal.com,https://www.trustpilot.com/review/dlocal.com,https://ibb.co/qCfg49D#(lf)M082-2,M082,Uruguay,URY,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M082-3,M082,Uruguay,URY,S0e3d54f3e7b6,Abitab,Abitab,Alternative 2,https://abitab.com.uy,https://www.crunchbase.com/organization/abitab,https://ibb.co/fM989nh#(lf)M083-1,M083,Serbia,SRB,S851925fb67ea,Diners Club,Diners Club,Primary,https://dinersclub.com,https://www.trustpilot.com/review/dinersclub.com,https://ibb.co/sCyLM9p#(lf)M083-2,M083,Serbia,SRB,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M083-3,M083,Serbia,SRB,Scfe1ae6e7f3a,Google Pay,Google Pay,Alternative 2,https://pay.google.com,https://www.pcmag.com/reviews/google-pay,https://ibb.co/bK79xby#(lf)M084-1,M084,Tanzania,TZA,S53db2806be5a,M-Pesa,M-Pesa,Primary,https://mpesa.com,https://tech-ish.com/2021/02/01/new-m-pesa-app-really-good/,https://ibb.co/85ZHXB9#(lf)M084-2,M084,Tanzania,TZA,S2cae73bdcb7c,Really Pesa,Really Pesa,Alternative 1,https://pesa.co,https://play.google.com/store/apps/details?id=com.mdqqkj.hakikaloan&hl=en-US,https://ibb.co/MnG2zBy#(lf)M084-3,M084,Tanzania,TZA,S53db2806be5a,M-Pesa,M-Pesa,Alternative 2,https://vodacom.co.tz,https://play.google.com/store/apps/details?id=com.vodafone.mpesa.tanzania&hl=en,https://ibb.co/bKMjw9h#(lf)M085-1,M085,Azerbaijan,AZE,Sfb8965ab4a52,AniPay,AniPay,Primary,https://anipay.az,https://appshunter.io/ios/app/1546614615,https://ibb.co/XYGcjmV#(lf)M085-2,M085,Azerbaijan,AZE,S95ba4ed9329f,Click,Click,Alternative 1,https://click.uz,https://ca.trustpilot.com/review/click.uz,https://ibb.co/K0MHQLK#(lf)M085-3,M085,Azerbaijan,AZE,Se2ad46d3f48e,AzeriPay,AzeriPay,Alternative 2,https://azericard.com,https://ratex42.com/listings/azericard/#(#)respond,https://ibb.co/4wyqDQM#(lf)M086-1,M086,Ghana,GHA,S57b68256e28f,MTN Mobile Money,MTN Mobile Money,Primary,https://momo.mtn.com,https://pctechmag.com/2020/05/mtn-momo-app-review/,https://ibb.co/XC141GY#(lf)M086-2,M086,Ghana,GHA,S4e3de48b0f3a,Hubtel,Hubtel,Alternative 1,https://hubtel.com,https://play.google.com/store/apps/details?id=com.hubtel.hcb&hl=en-US,https://ibb.co/Lhj5d1Z#(lf)M086-3,M086,Ghana,GHA,S6db696456e43,AirtelTigo,AirtelTigo,Alternative 2,https://airteltigo.com.gh,https://www.trustpilot.com/review/www.airteltigo.com.gh,https://ibb.co/2v36hhS#(lf)M087-1,M087,Slovenia,SVN,S4a523f589732,Moneta,Moneta,Primary,https://moneta.ru,https://partnerkin.com/services/monetaru/reviews,https://ibb.co/HThCR22#(lf)M087-2,M087,Slovenia,SVN,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M087-3,M087,Slovenia,SVN,S9518f42ad7fb,Google Wallet,Google wallet,Alternative 2,https://wallet.google/intl/,https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel&hl=en_IN,https://ibb.co/5rHX5jD#(lf)M088-1,M088,Belarus,BLR,Sb58ff996311b,Oplata,Oplata,Primary,https://belkart.by,https://belkart-pay.en.softonic.com/android,https://ibb.co/mS3JH82#(lf)M088-2,M088,Belarus,BLR,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M088-3,M088,Belarus,BLR,Scc9155d76e81,Yandex.Money,Yandex.Money,Alternative 2,https://bank.yandex.ru/pay,https://www.trustpilot.com/review/yandex.com,https://ibb.co/Fw3qJjF#(lf)M089-1,M089,DR Congo,COD,S91c395c3c9e0,Airtel Money,Airtel Money,Primary,https://mpesa.com,https://tech-ish.com/2021/02/01/new-m-pesa-app-really-good/,https://ibb.co/85ZHXB9#(lf)M089-2,M089,DR Congo,COD,S30438e444cb9,Orange Money,Orange Money,Alternative 1,https://orange.com,https://africanreview.com/finance/banking-a-finance/orange-money-fintech-is-proving-a-game-changer-in-africa,https://ibb.co/km2XBR6#(lf)M089-3,M089,DR Congo,COD,S04dad77b6120,Velmie,Velmie,Alternative 2,https://velmie.com,https://www.trustpilot.com/review/velmie.com,https://ibb.co/nkHyRHv#(lf)M090-1,M090,Myanmar,MMR,S819ffe68a604,Wave Money,Wave Money,Primary,https://wavemoney.com.mm,https://appshunter.io/ios/app/1439175549,https://ibb.co/QdbRSfP#(lf)M090-2,M090,Myanmar,MMR,S0a364d6b3a0b,Ongo,Ongo,Alternative 1,https://ongo.com.mm,https://rocketreach.co/ongo-e-money-profile_b5b5f3c7f63d2715,https://ibb.co/K0MHQLK#(lf)M090-3,M090,Myanmar,MMR,Sc92ee581fa42,KBZ Pay,KBZ Pay,Alternative 2,https://kbzpay.com,https://justuseapp.com/en/app/1398852297/kbzpay-customer/reviews,https://ibb.co/RNG3zfV#(lf)M091-1,M091,Uganda,UGA,S57b68256e28f,MTN Mobile Money,MTN Mobile Money,Primary,https://momo.mtn.com,https://pctechmag.com/2020/05/mtn-momo-app-review/,https://ibb.co/XC141GY#(lf)M091-2,M091,Uganda,UGA,Sb644e31f390d,Airtel Uganda,Airtel Uganda,Alternative 1,https://airtel.co.ug,https://tech-ish.com/2021/02/01/new-m-pesa-app-really-good/,https://ibb.co/vZxkyDR#(lf)M091-3,M091,Uganda,UGA,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M092-1,M092,Macau,MAC,S81b0fd1b771e,Macau Pass,Macau Pass,Primary,https://macaupass.com,https://play.google.com/store/apps/details/MPay?id=com.macaupass.rechargeEasy&hl=en-US,https://ibb.co/syhwnmx#(lf)M092-2,M092,Macau,MAC,Sd5b72847b212,Alipay,Alipay,Alternative 1,https://alipay.com,https://www.rapyd.net/blog/what-is-alipay/,https://ibb.co/ysHqJN4#(lf)M092-3,M092,Macau,MAC,Sa39c6414ea1e,WeChat Pay,WeChat Pay,Alternative 2,https://pay.wechat.com,https://www.tripadvisor.in/ShowTopic-g294211-i642-k14971097-WeChat_Pay_enables_digital_payment_of_8_foreign_e_wallets-China.html,https://ibb.co/G5fM7vQ#(lf)M093-1,M093,Cameroon,CMR,S30438e444cb9,Orange Money,Orange Money,Primary,https://orange.com,https://africanreview.com/finance/banking-a-finance/orange-money-fintech-is-proving-a-game-changer-in-africa,https://ibb.co/0MptPcg#(lf)M093-2,M093,Cameroon,CMR,S57b68256e28f,MTN Mobile Money,MTN Mobile Money,Alternative 1,https://momo.mtn.com,https://pctechmag.com/2020/05/mtn-momo-app-review/,https://ibb.co/3WqkHHt#(lf)M093-3,M093,Cameroon,CMR,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M094-1,M094,Jordan,JOR,Sfb1c3e32ff7c,Zain Cash,Zain Cash,Primary,https://zaincash.iq,https://www.appbrain.com/app/zaincash-%D8%B2%D9%8A%D9%86-%D9%83%D8%A7%D8%B4/mobi.foo.zaincash,https://ibb.co/vkKXkkD#(lf)M094-2,M094,Jordan,JOR,S9bd75a3fb14a,Reflect,Reflect,Alternative 1,https://pal.reflectapp.com,https://play.google.com/store/apps/details?id=com.arabbank.neobank&hl=en-US,https://ibb.co/v4gDFyY#(lf)M094-3,M094,Jordan,JOR,Sc7d464d29ff2,AnyPay,AnyPay,Alternative 2,https://anypay.co.th,https://www.scam-detector.com/validator/anypay-io-review/,https://ibb.co/rvjmcdJ#(lf)M095-1,M095,Tunisia,TUN,S742a084076c8,E-dinar,E-dinar,Primary,https://play.google.com/store/apps/details?id=com.kaoun.flouci&hl=en,https://read 4 flouci reviews (2025) | flouci.com reviews,https://ibb.co/q1hPhBg#(lf)M095-2,M095,Tunisia,TUN,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M095-3,M095,Tunisia,TUN,S4b4db0817515,TWINT,Twint,Alternative 2,https://twint.ch,https://www.trustpilot.com/review/www.twint.ch,https://ibb.co/py5DyNY#(lf)M096-1,M096,Cambodia,KHM,S4c6134be7015,Pi Pay,Pi Pay,Primary,https://pipay.com,https://appshunter.io/ios/app/1234143591,https://ibb.co/vzLpkwg#(lf)M096-2,M096,Cambodia,KHM,Sea0c0ee3ba62,ABA Mobile,ABA Mobile,Alternative 1,https://ababank.com,https://play.google.com/store/apps/details?id=com.paygo24.ibank&hl=en_IN,https://ibb.co/3W34yQW#(lf)M096-3,M096,Cambodia,KHM,Sc72302fe2fa0,Wing Bank,Wing Bank,Alternative 2,https://wingbank.com.kh,https://appshunter.io/ios/app/1113286385,https://ibb.co/GQbMYht#(lf)M097-1,M097,Bolivia,BOL,S8ce839d84089,Tigo Money,Tigo Money,Primary,https://tigomoney.com,https://tigo-money-bolivia.en.softonic.com/android,https://ibb.co/XY5CKXH#(lf)M097-2,M097,Bolivia,BOL,S46c79b38cace,PagoEfectivo,PagoEfectivo,Alternative 1,https://pagoefectivo.pe,https://www.linkedin.com/pulse/pagoefectivo-transforming-cash-payments-peruvian-tony-cueva-bravo-ae8ke,https://ibb.co/jJZj29h#(lf)M097-3,M097,Bolivia,BOL,Sab8a4f6bb84d,PayPal,PayPal,Alternative 2,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M098-1,M098,Bahrain,BHR,S49f1fb437cf1,Benefit Pay,Benefit Pay,Primary,https://benefit.bh,https://download.cnet.com/benefitpay/3000-2057_4-78509523.html,https://ibb.co/wBrjY3c#(lf)M098-2,M098,Bahrain,BHR,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M098-3,M098,Bahrain,BHR,S464d23b54f26,Tap,Tap,Alternative 2,https://tap.company,https://www.trustpilot.com/review/tap.company,https://ibb.co/fqT1scD#(lf)M099-1,M099,Latvia,LVA,Sab5445957d32,Mobilly,Mobilly,Primary,https://swedbank.com,https://appshunter.io/ios/app/344161302,https://ibb.co/n8tBqxR#(lf)M099-2,M099,Latvia,LVA,Sab8a4f6bb84d,PayPal,PayPal,Alternative 1,https://paypal.com,https://www.cnet.com/reviews/paypal-review/,https://ibb.co/JxbrsQ1#(lf)M099-3,M099,Latvia,LVA,S9518f42ad7fb,Google Wallet,Google wallet,Alternative 2,https://wallet.google/intl/,https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel&hl=en_IN,https://ibb.co/5rHX5jD#(lf)M100-1,M100,Paraguay,PRY,S8ce839d84089,Tigo Money,Tigo Money,Primary,https://tigo money,https://tigo-money-bolivia.en.softonic.com/android,https://ibb.co/z2YF9B1#(lf)M100-2,M100,Paraguay,PRY,Sfe7479645397,Personal Pay,Personal Pay,Alternative 1,https://personalpay.com,https://play.google.com/store/apps/details?id=ar.com.personalpay&hl=en_IN,https://ibb.co/0KZD4tk#(lf)M100-3,M100,Paraguay,PRY,Sa725bda1f33e,Visa,Visa,Alternative 2,https://visa.com,https://www.trustpilot.com/review/visa.com,https://ibb.co/RSSHY9w#(lf)\", TextEncoding.Utf8), [Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"listing_id\", type text}, {\"market_id\", type text}, {\"country\", type text}, {\"service_id\", type text}, {\"service\", type text}, {\"role\", type text}, {\"website\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Markets",
        "columns": [
          {
            "name": "Market ID",
            "dataType": "string",
            "lineageTag": "934bfeed-3fda-4417-9c91-0147fb75364e",
            "sourceColumn": "market_id",
            "summarizeBy": "none"
          },
          {
            "name": "Market",
            "dataType": "string",
            "lineageTag": "8c891ea9-1460-41b7-a992-8a00bce919a9",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "ISO3",
            "dataType": "string",
            "lineageTag": "05236f0b-44d7-4ecf-8b20-57df45666f09",
            "sourceColumn": "iso3",
            "summarizeBy": "none"
          },
          {
            "name": "Main service",
            "dataType": "string",
            "lineageTag": "50f6c77e-9dcb-4a79-9fa8-5897e9003112",
            "sourceColumn": "primary_service",
            "summarizeBy": "none"
          },
          {
            "name": "Alternative 1",
            "dataType": "string",
            "lineageTag": "dec03faf-8d2e-412a-a5d5-30e314c551e8",
            "sourceColumn": "alternative_1",
            "summarizeBy": "none"
          },
          {
            "name": "Alternative 2",
            "dataType": "string",
            "lineageTag": "313dd286-a3a4-4e20-a3d6-55a09227e111",
            "sourceColumn": "alternative_2",
            "summarizeBy": "none"
          },
          {
            "name": "Original share (unverified)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%",
            "lineageTag": "41c2d5de-9338-4ab3-ab21-42c95c8a5cce",
            "sourceColumn": "reported_share",
            "summarizeBy": "sum"
          },
          {
            "name": "Share status",
            "dataType": "string",
            "lineageTag": "7aad9bb1-7e8a-4ef7-aadc-3da02def1581",
            "sourceColumn": "share_status",
            "summarizeBy": "none"
          },
          {
            "name": "primary_service_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7961a440-be2e-4be9-81cf-b534ef6e74f9",
            "sourceColumn": "primary_service_id",
            "summarizeBy": "none"
          },
          {
            "name": "share_source_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48152d4f-e03a-4d00-86ae-fcc7a11febab",
            "sourceColumn": "share_source_url",
            "summarizeBy": "none"
          },
          {
            "name": "share_period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11af8ae7-8737-4868-b37f-21c1f07630f3",
            "sourceColumn": "share_period",
            "summarizeBy": "none"
          },
          {
            "name": "share_definition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1dc7f20-f786-44a2-b059-e608fc5ed819",
            "sourceColumn": "share_definition",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4e71b333-9912-45c3-bdfb-9b7b5c8cdb4a",
        "partitions": [
          {
            "name": "Markets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Text.ToBinary(\"market_id,country,iso3,primary_service,primary_service_id,reported_share,share_status,share_source_url,share_period,share_definition,alternative_1,alternative_2#(lf)M001,United States,USA,Apple Pay,S9bb3a91fbff8,0.43,Unverified,,,,Google Pay,PayPal#(lf)M002,China,CHN,Alipay,Sd5b72847b212,0.55,Unverified,,,,WeChat Pay,UnionPay#(lf)M003,Germany,DEU,PayPal,Sab8a4f6bb84d,0.32,Unverified,,,,Klarna,Sofort#(lf)M004,Japan,JPN,PayPay,S4d54ee71b475,0.31,Unverified,,,,LINE Pay,Rakuten Pay#(lf)M005,India,IND,PhonePe,Seb46c4263e56,0.47,Unverified,,,,Google Pay,Paytm#(lf)M006,United Kingdom,GBR,PayPal,Sab8a4f6bb84d,0.29,Unverified,,,,Apple Pay,Revolut#(lf)M007,France,FRA,Paylib,S4fe05e7db04b,0.24,Unverified,,,,Lydia,Google Pay#(lf)M008,Italy,ITA,Satispay,S4a84d0c48b14,0.2,Unverified,,,,Nexi,PayPal#(lf)M009,Canada,CAN,Interac,Sbd194199fe09,0.35,Unverified,,,,Apple Pay,Google Pay#(lf)M010,Brazil,BRA,PIX,S41b0635bb279,0.6,Unverified,,,,Mercado Pago,PayPal#(lf)M011,Russia,RUS,Yandex.Money,Scc9155d76e81,0.25,Unverified,,,,Qiwi,WebMoney#(lf)M012,South Korea,KOR,KakaoPay,Sc4987750ae1c,0.2,Unverified,,,,Samsung Pay,Naver Pay#(lf)M013,Australia,AUS,Afterpay,S032a27679a37,0.23,Unverified,,,,Zip Pay,PayPal#(lf)M014,Spain,ESP,Bizum,S09bf90a11ae3,0.42,Unverified,,,,PayPal,Apple Pay#(lf)M015,Mexico,MEX,Samsung Pay,Scd248346b654,0.3,Unverified,,,,Mercado Pago,PayPal#(lf)M016,Indonesia,IDN,OVO,S683e3175233e,0.4,Unverified,,,,GoPay,DANA#(lf)M017,Turkey,TUR,BKM Express,S12ca66653f33,0.3,Unverified,,,,PayPal,Ininal#(lf)M018,Netherlands,NLD,iDEAL,Sf54ab403ca1c,0.5,Unverified,,,,PayPal,SEPA#(lf)M019,Saudi Arabia,SAU,STC Pay,Sbc7ff7a28899,0.15,Unverified,,,,Apple Pay,PayPal#(lf)M020,Switzerland,CHE,TWINT,S4b4db0817515,0.25,Unverified,,,,PayPal,Apple Pay#(lf)M021,Poland,POL,BLIK,S354add2d89a1,0.44,Unverified,,,,Revolut,PayU#(lf)M022,Taiwan,TWN,LINE Pay,Se3a205bb818f,0.15,Unverified,,,,JkoPay,Apple Pay#(lf)M023,Belgium,BEL,Bancontact,S84e7c82fea0f,0.22,Unverified,,,,Payconiq,PayPal#(lf)M024,Sweden,SWE,Swish,S1e73623015d3,0.5,Unverified,,,,Klarna,PayPal#(lf)M025,Argentina,ARG,Mercado Pago,Sfe640272446b,0.54,Unverified,,,,Naranja X,Ualá#(lf)M026,Ireland,IRL,Revolut,Sdd53271a2e06,0.2,Unverified,,,,PayPal,N26#(lf)M027,United Arab Emirates,ARE,Apple Pay,S9bb3a91fbff8,0.3,Unverified,,,,Samsung Pay,Noon Pay#(lf)M028,Singapore,SGP,GrabPay,S09996930be63,0.35,Unverified,,,,PayNow,DBS PayLah#(lf)M029,Austria,AUT,MobilePay,Seecadce162c6,0.25,Unverified,,,,PayPal,Klarna#(lf)M030,Israel,ISR,Payoneer,S1c8aa3a6466b,0.2,Unverified,,,,BitPay,Isracard#(lf)M031,Thailand,THA,Rabbit Line Pay,S67799a5cdcb4,0.22,Unverified,,,,TrueMoney,Alipay#(lf)M032,Philippines,PHL,GCash,Seffe340b87b3,0.4,Unverified,,,,PayMaya,GrabPay#(lf)M033,Vietnam,VNM,MoMo,S4f61b35afbac,0.33,Unverified,,,,ZaloPay,Viettel Pay#(lf)M034,Norway,NOR,Vipps,S8c98ead1dc6f,0.22,Unverified,,,,PayPal,Apple Pay#(lf)M035,Malaysia,MYS,Touch 'n Go,Sda053fa8064d,0.27,Unverified,,,,CIMB OCTO MY,Boost#(lf)M036,Iran,IRN,Shetab,S1bd7750deb16,0.15,Unverified,,,,Zarinpal,Pay.ir#(lf)M037,Bangladesh,BGD,bKash,S5dbff7563966,0.43,Unverified,,,,Nagad,Rocket#(lf)M038,Denmark,DNK,MobilePay,Seecadce162c6,0.3,Unverified,,,,Apple Pay,Google Pay#(lf)M039,Hong Kong,HKG,Alipay,Sd5b72847b212,0.3,Unverified,,,,WeChat Pay,Octopus#(lf)M040,Colombia,COL,Nequi,Sb059c7cc919f,0.18,Unverified,,,,Daviplata,Bancolombia#(lf)M041,South Africa,ZAF,SnapScan,S712542eb0998,0.15,Unverified,,,,Zapper,PayPal#(lf)M042,Romania,ROU,MobilePay,Seecadce162c6,0.2,Unverified,,,,PayU,Revolut#(lf)M043,Egypt,EGY,Fawry,Se9bcb76e743e,0.25,Unverified,,,,myfawry,Aman#(lf)M044,Pakistan,PAK,JazzCash,Sa0b41fabd1f4,0.3,Unverified,,,,EasyPaisa,PayPal#(lf)M045,Chile,CHL,WebPay,S722f7eba24a7,0.25,Unverified,,,,Transbank,Khipu#(lf)M046,Czech Republic,CZE,GoPay,S177eb549798b,0.2,Unverified,,,,PayPal,Apple Pay#(lf)M047,Finland,FIN,MobilePay,Seecadce162c6,0.3,Unverified,,,,Siirto,PayPal#(lf)M048,Portugal,PRT,MB Way,Sa70a35b72c22,0.2,Unverified,,,,PayPal,Revolut#(lf)M049,Hungary,HUN,SimplePay,S19ce229ca0ea,0.25,Unverified,,,,Barion,PayPal#(lf)M050,Kazakhstan,KAZ,Kaspi.kz,S355387169087,0.35,Unverified,,,,Halyk Bank,Paybox#(lf)M051,Peru,PER,Yape,S560f89b4e57b,0.35,Unverified,,,,Banca Móvil BCP,Niubiz#(lf)M052,Iraq,IRQ,Zain Cash,Sfb1c3e32ff7c,0.1,Unverified,,,,Qi Services,FastPay#(lf)M053,Greece,GRC,Viva Wallet,Seff765f55a78,0.2,Unverified,,,,PayPal,Revolut#(lf)M054,Algeria,DZA,Barid Bank,S3bf830ec58e4,0.15,Unverified,,,,CIB,CashAddress#(lf)M055,New Zealand,NZL,Apple Pay,S9bb3a91fbff8,0.25,Unverified,,,,Afterpay,PayPal#(lf)M056,Qatar,QAT,Ooredoo Money,S6de18e00d6b3,0.2,Unverified,,,,Binance,CBQ Mobile#(lf)M057,Ethiopia,ETH,M-Birr,S721a27a1aa5e,0.2,Unverified,,,,Payoneer,Amole#(lf)M058,Nigeria,NGA,Paystack,S8421e6a3d5ee,0.3,Unverified,,,,Flutterwave,Moniepoint#(lf)M059,Ukraine,UKR,PrivatBank,Safbffd978275,0.25,Unverified,,,,Monobank,PUMB#(lf)M060,Morocco,MAR,Wafacash,S6f21be3f4238,0.15,Unverified,,,,CIH Mobile,Cash Plus#(lf)M061,Kuwait,KWT,KNET,Sc43969a3bafd,0.2,Unverified,,,,PayPal,Apple Pay#(lf)M062,Cuba,CUB,Transfermóvil,Sb1b70335837f,0.1,Unverified,,,,EnZona,Moneda U#(lf)M063,Slovakia,SVK,VIAMO,Sdc665e6c8a2c,0.1,Unverified,,,,PayPal,Apple Pay#(lf)M064,Dominican Republic,DOM,Orange Money,S30438e444cb9,0.1,Unverified,,,,Billet,PayPal#(lf)M065,Uzbekistan,UZB,Click,S95ba4ed9329f,0.15,Unverified,,,,Payme,UzCard#(lf)M066,Bulgaria,BGR,ePay,S4d8fcc240109,0.2,Unverified,,,,PayPal,EasyPay#(lf)M067,Ecuador,ECU,Kushki,S8bb8de8cc73e,0.15,Unverified,,,,PICHINCHA BANCA,PayPal#(lf)M068,Puerto Rico,PRI,ATH Móvil,Sa186ae7a8096,0.4,Unverified,,,,PayPal,Venmo#(lf)M069,Kenya,KEN,M-Pesa,S53db2806be5a,0.45,Unverified,,,,Loop,T-Kash#(lf)M070,Angola,AGO,ZAP,S94f173f4b39c,0.1,Unverified,,,,Easypay,GCash#(lf)M071,Guatemala,GTM,GCash,Seffe340b87b3,0.2,Unverified,,,,BANRURAL,MiDinero#(lf)M072,Oman,OMN,Oman Mobile Payment,S9b425f30fe38,0.1,Unverified,,,,PayCash,Bank Muscat#(lf)M073,Venezuela,VEN,Movilnet,S9656243ca723,0.15,Unverified,,,,Banco de Venezuela,PayPal#(lf)M074,Costa Rica,CRI,bank BCR,S5a33d5fbfbc5,0.15,Unverified,,,,BAC Credomatic,PayPal#(lf)M075,Luxembourg,LUX,Payconiq,S658e993fb9d6,0.1,Unverified,,,,PayPal,TWINT#(lf)M076,Croatia,HRV,AirCash,S8409bece1699,0.15,Unverified,,,,PayPal,Vertex#(lf)M077,Panama,PAN,Yappy,S2a2a83212153,0.2,Unverified,,,,PayPal,Banistmo#(lf)M078,Ivory Coast,CIV,Orange Money,S30438e444cb9,0.3,Unverified,,,,MTN Mobile Money,MoMo#(lf)M079,Sri Lanka,LKA,Dialog eZ Cash,Sd289ae1c3730,0.15,Unverified,,,,Sampath e-Wallet,PayPal#(lf)M080,Turkmenistan,TKM,Çapar Pay,S813979cbe3f6,0.1,Unverified,,,,Galkan töleg,e gov tm#(lf)M081,Lithuania,LTU,Paysera,Sfd6f7a606c5b,0.2,Unverified,,,,Revolut,TransferGo#(lf)M082,Uruguay,URY,dLocal,S1f12994d9b0c,0.25,Unverified,,,,PayPal,Abitab#(lf)M083,Serbia,SRB,Diners Club,S851925fb67ea,0.15,Unverified,,,,PayPal,Google Pay#(lf)M084,Tanzania,TZA,M-Pesa,S53db2806be5a,0.3,Unverified,,,,Really Pesa,M-Pesa#(lf)M085,Azerbaijan,AZE,AniPay,Sfb8965ab4a52,0.1,Unverified,,,,Click,AzeriPay#(lf)M086,Ghana,GHA,MTN Mobile Money,S57b68256e28f,0.4,Unverified,,,,Hubtel,AirtelTigo#(lf)M087,Slovenia,SVN,Moneta,S4a523f589732,0.15,Unverified,,,,PayPal,Google Wallet#(lf)M088,Belarus,BLR,Oplata,Sb58ff996311b,0.1,Unverified,,,,PayPal,Yandex.Money#(lf)M089,DR Congo,COD,Airtel Money,S91c395c3c9e0,0.25,Unverified,,,,Orange Money,Velmie#(lf)M090,Myanmar,MMR,Wave Money,S819ffe68a604,0.15,Unverified,,,,Ongo,KBZ Pay#(lf)M091,Uganda,UGA,MTN Mobile Money,S57b68256e28f,0.25,Unverified,,,,Airtel Uganda,PayPal#(lf)M092,Macau,MAC,Macau Pass,S81b0fd1b771e,0.15,Unverified,,,,Alipay,WeChat Pay#(lf)M093,Cameroon,CMR,Orange Money,S30438e444cb9,0.15,Unverified,,,,MTN Mobile Money,PayPal#(lf)M094,Jordan,JOR,Zain Cash,Sfb1c3e32ff7c,0.1,Unverified,,,,Reflect,AnyPay#(lf)M095,Tunisia,TUN,E-dinar,S742a084076c8,0.2,Unverified,,,,PayPal,TWINT#(lf)M096,Cambodia,KHM,Pi Pay,S4c6134be7015,0.15,Unverified,,,,ABA Mobile,Wing Bank#(lf)M097,Bolivia,BOL,Tigo Money,S8ce839d84089,0.15,Unverified,,,,PagoEfectivo,PayPal#(lf)M098,Bahrain,BHR,Benefit Pay,S49f1fb437cf1,0.2,Unverified,,,,PayPal,Tap#(lf)M099,Latvia,LVA,Mobilly,Sab5445957d32,0.15,Unverified,,,,PayPal,Google Wallet#(lf)M100,Paraguay,PRY,Tigo Money,S8ce839d84089,0.15,Unverified,,,,Personal Pay,Visa#(lf)\", TextEncoding.Utf8), [Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"market_id\", type text}, {\"country\", type text}, {\"iso3\", type text}, {\"primary_service\", type text}, {\"alternative_1\", type text}, {\"alternative_2\", type text}, {\"reported_share\", type number}, {\"share_status\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Services",
        "columns": [
          {
            "name": "Service ID",
            "dataType": "string",
            "lineageTag": "2d9ca5a1-0c82-4bc8-aae5-0a394798e15a",
            "sourceColumn": "service_id",
            "summarizeBy": "none"
          },
          {
            "name": "Service",
            "dataType": "string",
            "lineageTag": "42df48ce-7a0b-46be-aa86-7d0091453cfd",
            "sourceColumn": "service",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "acf1e736-db2f-440c-bee3-02d2e0f79102",
        "partitions": [
          {
            "name": "Services",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Text.ToBinary(\"service_id,service#(lf)Sea0c0ee3ba62,ABA Mobile#(lf)Sa186ae7a8096,ATH Móvil#(lf)S0e3d54f3e7b6,Abitab#(lf)S032a27679a37,Afterpay#(lf)S8409bece1699,AirCash#(lf)S91c395c3c9e0,Airtel Money#(lf)Sb644e31f390d,Airtel Uganda#(lf)S6db696456e43,AirtelTigo#(lf)Sd5b72847b212,Alipay#(lf)See286ba33708,Aman#(lf)Sfc8e27f609f4,Amole#(lf)Sfb8965ab4a52,AniPay#(lf)Sc7d464d29ff2,AnyPay#(lf)S9bb3a91fbff8,Apple Pay#(lf)Se2ad46d3f48e,AzeriPay#(lf)S847ed24aba8f,BAC Credomatic#(lf)S9ab007d4bdcf,BANRURAL#(lf)S12ca66653f33,BKM Express#(lf)S354add2d89a1,BLIK#(lf)S5e1d15a80a51,Banca Móvil BCP#(lf)S028fa62fc793,Banco de Venezuela#(lf)S8370f96e9d93,Bancolombia#(lf)S84e7c82fea0f,Bancontact#(lf)S6091bb1c77f0,Banistmo#(lf)S9fdb2b0725ab,Bank Muscat#(lf)S3bf830ec58e4,Barid Bank#(lf)S9f4c0a6f6150,Barion#(lf)S49f1fb437cf1,Benefit Pay#(lf)S2f77e8e6b5c1,Billet#(lf)Sf1624fcc63b6,Binance#(lf)Se1acedc90190,BitPay#(lf)S09bf90a11ae3,Bizum#(lf)S0d791a0a6f01,Boost#(lf)S0dbf7f12f197,CBQ Mobile#(lf)Sa9314df8e7a9,CIB#(lf)Sb3b4252796e8,CIH Mobile#(lf)S2d0bec069274,CIMB OCTO MY#(lf)Sa35b4fd24390,Cash Plus#(lf)Sb776149d47e3,CashAddress#(lf)S95ba4ed9329f,Click#(lf)S39dd0861d128,DANA#(lf)Sc953363739d2,DBS PayLah#(lf)S49b7ccf946a7,Daviplata#(lf)Sd289ae1c3730,Dialog eZ Cash#(lf)S851925fb67ea,Diners Club#(lf)S742a084076c8,E-dinar#(lf)S8a2d4c009231,EasyPaisa#(lf)Sf9b71269f6ff,EasyPay#(lf)Sf46b7c2274d4,Easypay#(lf)Sdc19504a356a,EnZona#(lf)S33e6460b0614,FastPay#(lf)Se9bcb76e743e,Fawry#(lf)S419c017fec88,Flutterwave#(lf)Seffe340b87b3,GCash#(lf)Sfe4df7a72733,Galkan töleg#(lf)S177eb549798b,GoPay#(lf)Scfe1ae6e7f3a,Google Pay#(lf)S9518f42ad7fb,Google Wallet#(lf)S09996930be63,GrabPay#(lf)S88853e062e22,Halyk Bank#(lf)S4e3de48b0f3a,Hubtel#(lf)Sc6f881bfe8f5,Ininal#(lf)Sbd194199fe09,Interac#(lf)Sf2bcbe5abd94,Isracard#(lf)Sa0b41fabd1f4,JazzCash#(lf)Sb0c9e4b4309e,JkoPay#(lf)Sc92ee581fa42,KBZ Pay#(lf)Sc43969a3bafd,KNET#(lf)Sc4987750ae1c,KakaoPay#(lf)S355387169087,Kaspi.kz#(lf)S888804c60126,Khipu#(lf)Sa2e779358d0d,Klarna#(lf)S8bb8de8cc73e,Kushki#(lf)Se3a205bb818f,LINE Pay#(lf)Sf2f6a0188995,Loop#(lf)S5a28fa1fccb6,Lydia#(lf)S721a27a1aa5e,M-Birr#(lf)S53db2806be5a,M-Pesa#(lf)Sa70a35b72c22,MB Way#(lf)S57b68256e28f,MTN Mobile Money#(lf)S81b0fd1b771e,Macau Pass#(lf)Sfe640272446b,Mercado Pago#(lf)S42fa0795c14e,MiDinero#(lf)S4f61b35afbac,MoMo#(lf)Seecadce162c6,MobilePay#(lf)Sab5445957d32,Mobilly#(lf)S716188579105,Moneda U#(lf)S4a523f589732,Moneta#(lf)Sf465788dea89,Moniepoint#(lf)S9722e8c42d66,Monobank#(lf)S9656243ca723,Movilnet#(lf)Sb86ee665f29a,N26#(lf)S1eb67b986588,Nagad#(lf)Sb4047e184273,Naranja X#(lf)S7906b84d8f9d,Naver Pay#(lf)Sb059c7cc919f,Nequi#(lf)S24ef7ec7e764,Nexi#(lf)S0f07802df56d,Niubiz#(lf)S22f85bf6fa63,Noon Pay#(lf)S683e3175233e,OVO#(lf)Sa7c7b3a28a61,Octopus#(lf)S9b425f30fe38,Oman Mobile Payment#(lf)S0a364d6b3a0b,Ongo#(lf)S6de18e00d6b3,Ooredoo Money#(lf)Sb58ff996311b,Oplata#(lf)S30438e444cb9,Orange Money#(lf)S1b57eeacfbd3,PICHINCHA BANCA#(lf)S41b0635bb279,PIX#(lf)S84287a10e6fb,PUMB#(lf)S46c79b38cace,PagoEfectivo#(lf)Sd2cb4f99541e,Pay.ir#(lf)Sd274d9c0228d,PayCash#(lf)Scc2cd9293700,PayMaya#(lf)S5c5af06729d3,PayNow#(lf)Sab8a4f6bb84d,PayPal#(lf)S4d54ee71b475,PayPay#(lf)S97aaa5725e62,PayU#(lf)S1b96cf56a09b,Paybox#(lf)S658e993fb9d6,Payconiq#(lf)S4fe05e7db04b,Paylib#(lf)Sf06f0269cf5d,Payme#(lf)S1c8aa3a6466b,Payoneer#(lf)Sfd6f7a606c5b,Paysera#(lf)S8421e6a3d5ee,Paystack#(lf)Sb2a940b2a2ea,Paytm#(lf)Sfe7479645397,Personal Pay#(lf)Seb46c4263e56,PhonePe#(lf)S4c6134be7015,Pi Pay#(lf)Safbffd978275,PrivatBank#(lf)S87bb80aa218c,Qi Services#(lf)S78832fd1d06f,Qiwi#(lf)S67799a5cdcb4,Rabbit Line Pay#(lf)S943d2ae40a1e,Rakuten Pay#(lf)S2cae73bdcb7c,Really Pesa#(lf)S9bd75a3fb14a,Reflect#(lf)Sdd53271a2e06,Revolut#(lf)Sd40a5aca994e,Rocket#(lf)S832c3b1ba488,SEPA#(lf)Sbc7ff7a28899,STC Pay#(lf)S4dc53e64465b,Sampath e-Wallet#(lf)Scd248346b654,Samsung Pay#(lf)S4a84d0c48b14,Satispay#(lf)S1bd7750deb16,Shetab#(lf)S3e68d4365d41,Siirto#(lf)S19ce229ca0ea,SimplePay#(lf)S712542eb0998,SnapScan#(lf)S02f195c0ad8e,Sofort#(lf)S1e73623015d3,Swish#(lf)Sb1a34ffcbfc3,T-Kash#(lf)S4b4db0817515,TWINT#(lf)S464d23b54f26,Tap#(lf)S8ce839d84089,Tigo Money#(lf)Sda053fa8064d,Touch 'n Go#(lf)Se2d8004648db,Transbank#(lf)S0e8f6fd2e105,TransferGo#(lf)Sb1b70335837f,Transfermóvil#(lf)S06780a7a437a,TrueMoney#(lf)Sa76287c409c4,Ualá#(lf)Sf926e95ae759,UnionPay#(lf)S6e23756c3c9b,UzCard#(lf)Sdc665e6c8a2c,VIAMO#(lf)S04dad77b6120,Velmie#(lf)Sa1593ecc5a13,Venmo#(lf)Saaabb660e287,Vertex#(lf)S556d78f4690a,Viettel Pay#(lf)S8c98ead1dc6f,Vipps#(lf)Sa725bda1f33e,Visa#(lf)Seff765f55a78,Viva Wallet#(lf)S6f21be3f4238,Wafacash#(lf)S819ffe68a604,Wave Money#(lf)Sa39c6414ea1e,WeChat Pay#(lf)S8e61bf5c793c,WebMoney#(lf)S722f7eba24a7,WebPay#(lf)Sc72302fe2fa0,Wing Bank#(lf)Scc9155d76e81,Yandex.Money#(lf)S560f89b4e57b,Yape#(lf)S2a2a83212153,Yappy#(lf)S94f173f4b39c,ZAP#(lf)Sfb1c3e32ff7c,Zain Cash#(lf)Sfb4a70e1beb4,ZaloPay#(lf)S088cc9c6f49b,Zapper#(lf)S4497ba648fd9,Zarinpal#(lf)S81b959cfba68,Zip Pay#(lf)S5dbff7563966,bKash#(lf)S5a33d5fbfbc5,bank BCR#(lf)S1f12994d9b0c,dLocal#(lf)S99aa3e6c42cc,e gov tm#(lf)S4d8fcc240109,ePay#(lf)Sf54ab403ca1c,iDEAL#(lf)Sf63ecf4435b0,myfawry#(lf)S813979cbe3f6,Çapar Pay#(lf)\", TextEncoding.Utf8), [Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"service_id\", type text}, {\"service\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Review",
        "columns": [
          {
            "name": "Market ID",
            "dataType": "string",
            "lineageTag": "7c0ae62c-2bd2-482a-a959-fcec7b26cc5b",
            "sourceColumn": "market_id",
            "summarizeBy": "none"
          },
          {
            "name": "Market",
            "dataType": "string",
            "lineageTag": "c7faabbb-d94e-4e8b-82a7-66a8d4b58e5d",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "Issue",
            "dataType": "string",
            "lineageTag": "294a20f6-554a-4967-a594-e504ac7ae327",
            "sourceColumn": "issue",
            "summarizeBy": "none"
          },
          {
            "name": "Detail",
            "dataType": "string",
            "lineageTag": "b77487ab-f03f-4c31-a416-7b7c3d7bd544",
            "sourceColumn": "detail",
            "summarizeBy": "none"
          },
          {
            "name": "Next step",
            "dataType": "string",
            "lineageTag": "48cce963-9857-4176-827c-56c6e51b9b96",
            "sourceColumn": "next_step",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ab1a9005-46a3-40f5-814b-783b73fe774a",
        "partitions": [
          {
            "name": "Review",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Text.ToBinary(\"market_id,country,issue,detail,next_step#(lf)M001,United States,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M002,China,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M003,Germany,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M004,Japan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M005,India,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M006,United Kingdom,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M007,France,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M008,Italy,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M009,Canada,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M010,Brazil,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M011,Russia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M012,South Korea,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M013,Australia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M014,Spain,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M015,Mexico,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M016,Indonesia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M017,Turkey,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M018,Netherlands,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M019,Saudi Arabia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M020,Switzerland,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M021,Poland,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M022,Taiwan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M023,Belgium,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M024,Sweden,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M025,Argentina,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M026,Ireland,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M027,United Arab Emirates,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M028,Singapore,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M029,Austria,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M030,Israel,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M031,Thailand,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M032,Philippines,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M033,Vietnam,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M034,Norway,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M035,Malaysia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M036,Iran,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M037,Bangladesh,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M038,Denmark,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M039,Hong Kong,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M040,Colombia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M041,South Africa,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M042,Romania,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M043,Egypt,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M044,Pakistan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M045,Chile,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M046,Czech Republic,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M047,Finland,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M048,Portugal,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M049,Hungary,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M050,Kazakhstan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M051,Peru,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M052,Iraq,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M053,Greece,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M054,Algeria,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M055,New Zealand,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M056,Qatar,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M057,Ethiopia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M058,Nigeria,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M059,Ukraine,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M060,Morocco,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M061,Kuwait,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M062,Cuba,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M063,Slovakia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M064,Dominican Republic,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M065,Uzbekistan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M066,Bulgaria,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M067,Ecuador,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M068,Puerto Rico,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M069,Kenya,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M070,Angola,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M071,Guatemala,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M072,Oman,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M073,Venezuela,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M074,Costa Rica,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M075,Luxembourg,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M076,Croatia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M077,Panama,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M078,Ivory Coast,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M079,Sri Lanka,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M080,Turkmenistan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M081,Lithuania,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M082,Uruguay,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M083,Serbia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M084,Tanzania,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M085,Azerbaijan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M086,Ghana,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M087,Slovenia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M088,Belarus,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M089,DR Congo,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M090,Myanmar,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M091,Uganda,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M092,Macau,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M093,Cameroon,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M094,Jordan,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M095,Tunisia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M096,Cambodia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M097,Bolivia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M098,Bahrain,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M099,Latvia,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M100,Paraguay,Market-share evidence missing,\"\"Original share has no documented source, measurement period or denominator.\"\",Find the original source and record its period and definition before comparison.#(lf)M084,Tanzania,Repeated service in the same market,M-Pesa appears in more than one listed role. Coverage counts the market once.,Check the original research and replace the repeated alternative only with verified evidence.#(lf),All markets,Service and link verification pending,\"\"Original rows include wallets, payment networks and payment schemes. Website, review and screenshot links are unverified.\"\",\"\"Verify each service's identity, country availability and linked material against primary sources.\"\"#(lf)\", TextEncoding.Utf8), [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"market_id\", type text}, {\"country\", type text}, {\"issue\", type text}, {\"detail\", type text}, {\"next_step\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Changes",
        "columns": [
          {
            "name": "Market",
            "dataType": "string",
            "lineageTag": "f7ade3d0-938d-4b6b-ae64-b2588893713d",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "Field",
            "dataType": "string",
            "lineageTag": "313f8ed2-af92-4f26-a501-a29181e1d55c",
            "sourceColumn": "field",
            "summarizeBy": "none"
          },
          {
            "name": "Original",
            "dataType": "string",
            "lineageTag": "1839d191-37a0-4f38-be75-9cb068f1278e",
            "sourceColumn": "original",
            "summarizeBy": "none"
          },
          {
            "name": "Cleaned",
            "dataType": "string",
            "lineageTag": "d6683f82-9ebf-4b8c-b63f-56a51e70487a",
            "sourceColumn": "cleaned",
            "summarizeBy": "none"
          },
          {
            "name": "Reason",
            "dataType": "string",
            "lineageTag": "a464b8da-bc57-43db-ade4-4d2502c2f78a",
            "sourceColumn": "reason",
            "summarizeBy": "none"
          },
          {
            "name": "market_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88dde89e-3f6e-42fe-ab53-7143f69aeb08",
            "sourceColumn": "market_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3474603c-bf72-4b96-b230-b61f03fe5ee3",
        "partitions": [
          {
            "name": "Changes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Text.ToBinary(\"market_id,country,field,original,cleaned,reason#(lf)M001,United States,App Website Link,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M001,United States,Alternate1 Website,pay.google.com,https://pay.google.com,Add missing https scheme / normalize URL syntax#(lf)M001,United States,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M002,China,App Website Link,alipay.com,https://alipay.com,Add missing https scheme / normalize URL syntax#(lf)M002,China,Alternate1 Website,weixin.qq.com,https://weixin.qq.com,Add missing https scheme / normalize URL syntax#(lf)M002,China,Alternate2 Website,unionpayintl.com,https://unionpayintl.com,Add missing https scheme / normalize URL syntax#(lf)M003,Germany,App Website Link,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M003,Germany,Alternate1 Website,klarna.com,https://klarna.com,Add missing https scheme / normalize URL syntax#(lf)M003,Germany,Alternate2 Website,sofort.com,https://sofort.com,Add missing https scheme / normalize URL syntax#(lf)M004,Japan,App Website Link,paypay.ne.jp,https://paypay.ne.jp,Add missing https scheme / normalize URL syntax#(lf)M004,Japan,Alternate1 Website,pay.line.me,https://pay.line.me,Add missing https scheme / normalize URL syntax#(lf)M004,Japan,Alternate2 Website,rakuten.com,https://rakuten.com,Add missing https scheme / normalize URL syntax#(lf)M005,India,App Website Link,phonepe.com,https://phonepe.com,Add missing https scheme / normalize URL syntax#(lf)M005,India,Alternate1 Website,pay.google.com,https://pay.google.com,Add missing https scheme / normalize URL syntax#(lf)M005,India,Alternate2 Website,paytm.com,https://paytm.com,Add missing https scheme / normalize URL syntax#(lf)M006,United Kingdom,App Website Link,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M006,United Kingdom,Alternate1 Website,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M006,United Kingdom,Alternate2 Website,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M007,France,App Website Link,paylib.fr,https://paylib.fr,Add missing https scheme / normalize URL syntax#(lf)M007,France,Alternate1 Website,lydia-app.com,https://lydia-app.com,Add missing https scheme / normalize URL syntax#(lf)M007,France,Alternate2 Website,pay.google.com,https://pay.google.com,Add missing https scheme / normalize URL syntax#(lf)M008,Italy,App Website Link,satispay.com,https://satispay.com,Add missing https scheme / normalize URL syntax#(lf)M008,Italy,Alternate1 Website,nexi.it,https://nexi.it,Add missing https scheme / normalize URL syntax#(lf)M008,Italy,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M009,Canada,App Website Link,interac.ca,https://interac.ca,Add missing https scheme / normalize URL syntax#(lf)M009,Canada,Alternate1 Website,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M009,Canada,Alternate2 Website,pay.google.com,https://pay.google.com,Add missing https scheme / normalize URL syntax#(lf)M010,Brazil,App Website Link,mercadopago.com.br,https://mercadopago.com.br,Add missing https scheme / normalize URL syntax#(lf)M010,Brazil,Alternate1 Website,mercadopago.com,https://mercadopago.com,Add missing https scheme / normalize URL syntax#(lf)M010,Brazil,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M011,Russia,App Website Link,yoomoney.ru,https://yoomoney.ru,Add missing https scheme / normalize URL syntax#(lf)M011,Russia,Alternate1 Website,qiwi.com,https://qiwi.com,Add missing https scheme / normalize URL syntax#(lf)M011,Russia,Alternate2 Website,webmoney.ru,https://webmoney.ru,Add missing https scheme / normalize URL syntax#(lf)M012,South Korea,App Website Link,kakaopay.com,https://kakaopay.com,Add missing https scheme / normalize URL syntax#(lf)M012,South Korea,Alternate1 Website,samsung.com/samsung-pay,https://samsung.com/samsung-pay,Add missing https scheme / normalize URL syntax#(lf)M012,South Korea,Alternate2 Website,naver.com,https://naver.com,Add missing https scheme / normalize URL syntax#(lf)M013,Australia,App Website Link,afterpay.com,https://afterpay.com,Add missing https scheme / normalize URL syntax#(lf)M013,Australia,Alternate1 Website,zip.co,https://zip.co,Add missing https scheme / normalize URL syntax#(lf)M013,Australia,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M014,Spain,App Website Link,bizum.es,https://bizum.es,Add missing https scheme / normalize URL syntax#(lf)M014,Spain,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M014,Spain,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M015,Mexico,App Website Link,samsung.com/samsung-pay,https://samsung.com/samsung-pay,Add missing https scheme / normalize URL syntax#(lf)M015,Mexico,Alternate1 Website,mercadopago.com,https://mercadopago.com,Add missing https scheme / normalize URL syntax#(lf)M015,Mexico,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M016,Indonesia,App Website Link,ovo.id,https://ovo.id,Add missing https scheme / normalize URL syntax#(lf)M016,Indonesia,Alternate1 Website,gopay.co.id,https://gopay.co.id,Add missing https scheme / normalize URL syntax#(lf)M016,Indonesia,Alternate2 Website,dana.id,https://dana.id,Add missing https scheme / normalize URL syntax#(lf)M017,Turkey,App Website Link,bkm.com.tr,https://bkm.com.tr,Add missing https scheme / normalize URL syntax#(lf)M017,Turkey,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M017,Turkey,Alternate2 Website,ininal.com,https://ininal.com,Add missing https scheme / normalize URL syntax#(lf)M018,Netherlands,App Website Link,ideal.nl,https://ideal.nl,Add missing https scheme / normalize URL syntax#(lf)M018,Netherlands,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M018,Netherlands,Alternate2 Website,ecb.europa.eu,https://ecb.europa.eu,Add missing https scheme / normalize URL syntax#(lf)M019,Saudi Arabia,App Website Link,stcpay.com.sa,https://stcpay.com.sa,Add missing https scheme / normalize URL syntax#(lf)M019,Saudi Arabia,Alternate1 Website,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M019,Saudi Arabia,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M020,Switzerland,App Website Link,twint.ch,https://twint.ch,Add missing https scheme / normalize URL syntax#(lf)M020,Switzerland,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M020,Switzerland,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M021,Poland,App Website Link,blik.com,https://blik.com,Add missing https scheme / normalize URL syntax#(lf)M021,Poland,Alternate1 Website,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M021,Poland,Alternate2 Website,payu.com,https://payu.com,Add missing https scheme / normalize URL syntax#(lf)M022,Taiwan,App Name,Line Pay,LINE Pay,Trim whitespace / documented spelling or capitalization alias#(lf)M022,Taiwan,App Website Link,linepay.com,https://linepay.com,Add missing https scheme / normalize URL syntax#(lf)M022,Taiwan,Alternate1 Website,jkopay.com,https://jkopay.com,Add missing https scheme / normalize URL syntax#(lf)M022,Taiwan,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M023,Belgium,App Website Link,bancontact.com,https://bancontact.com,Add missing https scheme / normalize URL syntax#(lf)M023,Belgium,Alternate1 Website,payconiq.com,https://payconiq.com,Add missing https scheme / normalize URL syntax#(lf)M023,Belgium,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M024,Sweden,App Website Link,swish.nu,https://swish.nu,Add missing https scheme / normalize URL syntax#(lf)M024,Sweden,Alternate1 Website,klarna.com,https://klarna.com,Add missing https scheme / normalize URL syntax#(lf)M024,Sweden,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M025,Argentina,App Website Link,mercadopago.com,https://mercadopago.com,Add missing https scheme / normalize URL syntax#(lf)M025,Argentina,Alternate1 Website,naranjax.com,https://naranjax.com,Add missing https scheme / normalize URL syntax#(lf)M025,Argentina,Alternate2 Website,uala.com,https://uala.com,Add missing https scheme / normalize URL syntax#(lf)M026,Ireland,App Website Link,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M026,Ireland,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M026,Ireland,Alternate2 Website,n26.com,https://n26.com,Add missing https scheme / normalize URL syntax#(lf)M027,United Arab Emirates,App Website Link,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M027,United Arab Emirates,Alternate1 Website,samsung.com/samsung-pay,https://samsung.com/samsung-pay,Add missing https scheme / normalize URL syntax#(lf)M027,United Arab Emirates,Alternate2 Website,noon.com,https://noon.com,Add missing https scheme / normalize URL syntax#(lf)M028,Singapore,App Website Link,grab.com,https://grab.com,Add missing https scheme / normalize URL syntax#(lf)M028,Singapore,Alternate1 Website,abs.org.sg/consumer-banking/pay-now,https://abs.org.sg/consumer-banking/pay-now,Add missing https scheme / normalize URL syntax#(lf)M028,Singapore,Alternate2 Website,dbs.com.sg,https://dbs.com.sg,Add missing https scheme / normalize URL syntax#(lf)M029,Austria,App Name,Mobile Pay,MobilePay,Trim whitespace / documented spelling or capitalization alias#(lf)M029,Austria,App Website Link,mobilepay.dk,https://mobilepay.dk,Add missing https scheme / normalize URL syntax#(lf)M029,Austria,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M029,Austria,Alternate2 Website,klarna.com,https://klarna.com,Add missing https scheme / normalize URL syntax#(lf)M030,Israel,App Website Link,payoneer.com,https://payoneer.com,Add missing https scheme / normalize URL syntax#(lf)M030,Israel,Alternate1 Website,bitpay.com,https://bitpay.com,Add missing https scheme / normalize URL syntax#(lf)M030,Israel,Alternate2 Website,isracard.co.il,https://isracard.co.il,Add missing https scheme / normalize URL syntax#(lf)M031,Thailand,App Website Link,rabbit.co.th,https://rabbit.co.th,Add missing https scheme / normalize URL syntax#(lf)M031,Thailand,Alternate1 Website,truemoney.com,https://truemoney.com,Add missing https scheme / normalize URL syntax#(lf)M031,Thailand,Alternate2 Website,alipay.com,https://alipay.com,Add missing https scheme / normalize URL syntax#(lf)M032,Philippines,App Website Link,gcash.com,https://gcash.com,Add missing https scheme / normalize URL syntax#(lf)M032,Philippines,Alternate1 Website,paymaya.com,https://paymaya.com,Add missing https scheme / normalize URL syntax#(lf)M032,Philippines,Alternate2 Website,grab.com,https://grab.com,Add missing https scheme / normalize URL syntax#(lf)M033,Vietnam,App Website Link,momo.vn,https://momo.vn,Add missing https scheme / normalize URL syntax#(lf)M033,Vietnam,Alternate1 Website,zalopay.vn,https://zalopay.vn,Add missing https scheme / normalize URL syntax#(lf)M033,Vietnam,Alternate2 Website,viettelpay.vn,https://viettelpay.vn,Add missing https scheme / normalize URL syntax#(lf)M034,Norway,App Website Link,vipps.no,https://vipps.no,Add missing https scheme / normalize URL syntax#(lf)M034,Norway,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M034,Norway,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M035,Malaysia,App Website Link,touchngo.com.my,https://touchngo.com.my,Add missing https scheme / normalize URL syntax#(lf)M035,Malaysia,Alternate1 Website,cimb.com.my,https://cimb.com.my,Add missing https scheme / normalize URL syntax#(lf)M035,Malaysia,Alternate2 Website,myboost.co/,https://myboost.co/,Add missing https scheme / normalize URL syntax#(lf)M036,Iran,App Website Link,shetab.com,https://shetab.com,Add missing https scheme / normalize URL syntax#(lf)M036,Iran,Alternate1 Website,zarinpal.com,https://zarinpal.com,Add missing https scheme / normalize URL syntax#(lf)M036,Iran,Alternate2 Website,pay.ir,https://pay.ir,Add missing https scheme / normalize URL syntax#(lf)M037,Bangladesh,App Website Link,bkash.com,https://bkash.com,Add missing https scheme / normalize URL syntax#(lf)M037,Bangladesh,Alternate1 Website,nagad.com.bd,https://nagad.com.bd,Add missing https scheme / normalize URL syntax#(lf)M037,Bangladesh,Alternate2 Website,dutchbanglabank.com,https://dutchbanglabank.com,Add missing https scheme / normalize URL syntax#(lf)M038,Denmark,App Website Link,mobilepay.dk,https://mobilepay.dk,Add missing https scheme / normalize URL syntax#(lf)M038,Denmark,Alternate1 Website,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M038,Denmark,Alternate2 Name,Goggle Pay,Google Pay,Trim whitespace / documented spelling or capitalization alias#(lf)M038,Denmark,Alternate2 Website,pay.google.com,https://pay.google.com,Add missing https scheme / normalize URL syntax#(lf)M039,Hong Kong,App Website Link,alipay.com,https://alipay.com,Add missing https scheme / normalize URL syntax#(lf)M039,Hong Kong,Alternate1 Website,weixin.qq.com,https://weixin.qq.com,Add missing https scheme / normalize URL syntax#(lf)M039,Hong Kong,Alternate2 Website,octopus.com.hk,https://octopus.com.hk,Add missing https scheme / normalize URL syntax#(lf)M040,Colombia,App Website Link,nequi.com.co,https://nequi.com.co,Add missing https scheme / normalize URL syntax#(lf)M040,Colombia,Alternate1 Website,daviplata.com,https://daviplata.com,Add missing https scheme / normalize URL syntax#(lf)M040,Colombia,Alternate2 Website,bancolombia.com,https://bancolombia.com,Add missing https scheme / normalize URL syntax#(lf)M041,South Africa,App Website Link,snapscan.co.za,https://snapscan.co.za,Add missing https scheme / normalize URL syntax#(lf)M041,South Africa,Alternate1 Website,zapper.com,https://zapper.com,Add missing https scheme / normalize URL syntax#(lf)M041,South Africa,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M042,Romania,App Website Link,mobilepay.dk,https://mobilepay.dk,Add missing https scheme / normalize URL syntax#(lf)M042,Romania,Alternate1 Website,payu.com,https://payu.com,Add missing https scheme / normalize URL syntax#(lf)M042,Romania,Alternate2 Website,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M043,Egypt,App Website Link,fawry.com,https://fawry.com,Add missing https scheme / normalize URL syntax#(lf)M043,Egypt,Alternate1 Website,fawry.com,https://fawry.com,Add missing https scheme / normalize URL syntax#(lf)M043,Egypt,Alternate2 Website,aman.eg,https://aman.eg,Add missing https scheme / normalize URL syntax#(lf)M044,Pakistan,App Website Link,jazzcash.com.pk,https://jazzcash.com.pk,Add missing https scheme / normalize URL syntax#(lf)M044,Pakistan,Alternate1 Website,easypaisa.com.pk,https://easypaisa.com.pk,Add missing https scheme / normalize URL syntax#(lf)M044,Pakistan,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M045,Chile,App Website Link,webpay.cl,https://webpay.cl,Add missing https scheme / normalize URL syntax#(lf)M045,Chile,Alternate1 Website,transbank.cl,https://transbank.cl,Add missing https scheme / normalize URL syntax#(lf)M045,Chile,Alternate2 Website,khipu.com,https://khipu.com,Add missing https scheme / normalize URL syntax#(lf)M046,Czech Republic,App Website Link,gopay.co.id,https://gopay.co.id,Add missing https scheme / normalize URL syntax#(lf)M046,Czech Republic,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M046,Czech Republic,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M047,Finland,App Website Link,mobilepay.dk,https://mobilepay.dk,Add missing https scheme / normalize URL syntax#(lf)M047,Finland,Alternate1 Website,siirto.fi,https://siirto.fi,Add missing https scheme / normalize URL syntax#(lf)M047,Finland,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M048,Portugal,App Website Link,mbway.pt,https://mbway.pt,Add missing https scheme / normalize URL syntax#(lf)M048,Portugal,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M048,Portugal,Alternate2 Website,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M049,Hungary,App Website Link,simplepay.com,https://simplepay.com,Add missing https scheme / normalize URL syntax#(lf)M049,Hungary,Alternate1 Website,barion.com,https://barion.com,Add missing https scheme / normalize URL syntax#(lf)M049,Hungary,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M050,Kazakhstan,App Website Link,kaspi.kz,https://kaspi.kz,Add missing https scheme / normalize URL syntax#(lf)M050,Kazakhstan,Alternate1 Website,halykbank.kz,https://halykbank.kz,Add missing https scheme / normalize URL syntax#(lf)M050,Kazakhstan,Alternate2 Website,paybox.ru,https://paybox.ru,Add missing https scheme / normalize URL syntax#(lf)M051,Peru,App Website Link,yape.com.pe,https://yape.com.pe,Add missing https scheme / normalize URL syntax#(lf)M051,Peru,Alternate1 Website,www.pichincha.com/banca-movil,https://www.pichincha.com/banca-movil,Add missing https scheme / normalize URL syntax#(lf)M051,Peru,Alternate2 Website,niubiz.com.pe,https://niubiz.com.pe,Add missing https scheme / normalize URL syntax#(lf)M052,Iraq,App Website Link,zaincash.iq,https://zaincash.iq,Add missing https scheme / normalize URL syntax#(lf)M052,Iraq,Alternate1 Website,qi.iq/en/digital-zone,https://qi.iq/en/digital-zone,Add missing https scheme / normalize URL syntax#(lf)M052,Iraq,Alternate2 Website,fast-pay.iq,https://fast-pay.iq,Add missing https scheme / normalize URL syntax#(lf)M053,Greece,App Website Link,vivawallet.com,https://vivawallet.com,Add missing https scheme / normalize URL syntax#(lf)M053,Greece,Alternate1 Name,Paypal,PayPal,Trim whitespace / documented spelling or capitalization alias#(lf)M053,Greece,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M053,Greece,Alternate2 Website,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M054,Algeria,App Website Link,albaridbank.ma/fr/nos-solutions/barid-bank-mobile,https://albaridbank.ma/fr/nos-solutions/barid-bank-mobile,Add missing https scheme / normalize URL syntax#(lf)M054,Algeria,Alternate1 Website,cibeg.com,https://cibeg.com,Add missing https scheme / normalize URL syntax#(lf)M054,Algeria,Alternate2 Website,cashaddress.org,https://cashaddress.org,Add missing https scheme / normalize URL syntax#(lf)M055,New Zealand,App Website Link,apple.com/apple-pay,https://apple.com/apple-pay,Add missing https scheme / normalize URL syntax#(lf)M055,New Zealand,Alternate1 Website,afterpay.com,https://afterpay.com,Add missing https scheme / normalize URL syntax#(lf)M055,New Zealand,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M056,Qatar,App Website Link,ooredoo.qa/web/en/ooredoo-money/,https://ooredoo.qa/web/en/ooredoo-money/,Add missing https scheme / normalize URL syntax#(lf)M056,Qatar,Alternate1 Website,binance.com,https://binance.com,Add missing https scheme / normalize URL syntax#(lf)M056,Qatar,Alternate2 Website,cbq.qa,https://cbq.qa,Add missing https scheme / normalize URL syntax#(lf)M057,Ethiopia,App Website Link,m-birr.com,https://m-birr.com,Add missing https scheme / normalize URL syntax#(lf)M057,Ethiopia,Alternate1 Website,payoneer.com,https://payoneer.com,Add missing https scheme / normalize URL syntax#(lf)M057,Ethiopia,Alternate2 Website,dashenbanksc.com/amole-payment-services/,https://dashenbanksc.com/amole-payment-services/,Add missing https scheme / normalize URL syntax#(lf)M058,Nigeria,App Website Link,paystack.com,https://paystack.com,Add missing https scheme / normalize URL syntax#(lf)M058,Nigeria,Alternate1 Website,flutterwave.com,https://flutterwave.com,Add missing https scheme / normalize URL syntax#(lf)M058,Nigeria,Alternate2 Website,moniepoint.com,https://moniepoint.com,Add missing https scheme / normalize URL syntax#(lf)M059,Ukraine,App Website Link,privatbank.ua,https://privatbank.ua,Add missing https scheme / normalize URL syntax#(lf)M059,Ukraine,Alternate1 Website,monobank.ua,https://monobank.ua,Add missing https scheme / normalize URL syntax#(lf)M059,Ukraine,Alternate2 Website,pumb.ua,https://pumb.ua,Add missing https scheme / normalize URL syntax#(lf)M060,Morocco,App Website Link,wafacash.com,https://wafacash.com,Add missing https scheme / normalize URL syntax#(lf)M060,Morocco,Alternate1 Website,cihbank.ma,https://cihbank.ma,Add missing https scheme / normalize URL syntax#(lf)M060,Morocco,Alternate2 Website,cashplus.ma,https://cashplus.ma,Add missing https scheme / normalize URL syntax#(lf)M061,Kuwait,App Website Link,knet.com.kw,https://knet.com.kw,Add missing https scheme / normalize URL syntax#(lf)M061,Kuwait,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M061,Kuwait,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M062,Cuba,App Website Link,etecsa.cu/en/entrepreneurs/transfermovil,https://etecsa.cu/en/entrepreneurs/transfermovil,Add missing https scheme / normalize URL syntax#(lf)M062,Cuba,App Screenshot Link,Website Not Accessable,https://website not accessable,Add missing https scheme / normalize URL syntax#(lf)M062,Cuba,Alternate1 Website,www.enzona.net,https://www.enzona.net,Add missing https scheme / normalize URL syntax#(lf)M062,Cuba,Alternate2 Website,somosmoneda.app,https://somosmoneda.app,Add missing https scheme / normalize URL syntax#(lf)M063,Slovakia,App Website Link,viamo.io,https://viamo.io,Add missing https scheme / normalize URL syntax#(lf)M063,Slovakia,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M063,Slovakia,Alternate2 Website,apple.com/apple-pay/,https://apple.com/apple-pay/,Add missing https scheme / normalize URL syntax#(lf)M064,Dominican Republic,App Website Link,orange.com,https://orange.com,Add missing https scheme / normalize URL syntax#(lf)M064,Dominican Republic,Alternate1 Website,billet.do/,https://billet.do/,Add missing https scheme / normalize URL syntax#(lf)M064,Dominican Republic,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M065,Uzbekistan,App Website Link,click.uz,https://click.uz,Add missing https scheme / normalize URL syntax#(lf)M065,Uzbekistan,Alternate1 Website,payme.uz,https://payme.uz,Add missing https scheme / normalize URL syntax#(lf)M065,Uzbekistan,Alternate2 Website,uzcard.uz,https://uzcard.uz,Add missing https scheme / normalize URL syntax#(lf)M066,Bulgaria,App Website Link,epay.com,https://epay.com,Add missing https scheme / normalize URL syntax#(lf)M066,Bulgaria,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M066,Bulgaria,Alternate2 Website,easypay.ua,https://easypay.ua,Add missing https scheme / normalize URL syntax#(lf)M067,Ecuador,App Website Link,kushkipagos.com,https://kushkipagos.com,Add missing https scheme / normalize URL syntax#(lf)M067,Ecuador,Alternate1 Website,pichincha.com,https://pichincha.com,Add missing https scheme / normalize URL syntax#(lf)M067,Ecuador,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M068,Puerto Rico,App Website Link,athmovil.com,https://athmovil.com,Add missing https scheme / normalize URL syntax#(lf)M068,Puerto Rico,App Screenshot Link,Website Not Accessable,https://website not accessable,Add missing https scheme / normalize URL syntax#(lf)M068,Puerto Rico,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M068,Puerto Rico,Alternate2 Website,venmo.com,https://venmo.com,Add missing https scheme / normalize URL syntax#(lf)M069,Kenya,App Website Link,mpesa.com,https://mpesa.com,Add missing https scheme / normalize URL syntax#(lf)M069,Kenya,Alternate1 Website,loop.co.ke,https://loop.co.ke,Add missing https scheme / normalize URL syntax#(lf)M069,Kenya,Alternate2 Website,telkom.co.ke/,https://telkom.co.ke/,Add missing https scheme / normalize URL syntax#(lf)M070,Angola,App Website Link,zap.com,https://zap.com,Add missing https scheme / normalize URL syntax#(lf)M070,Angola,Alternate1 Website,easypay.com,https://easypay.com,Add missing https scheme / normalize URL syntax#(lf)M070,Angola,Alternate2 Website,gcash.com,https://gcash.com,Add missing https scheme / normalize URL syntax#(lf)M071,Guatemala,App Website Link,gcash.com,https://gcash.com,Add missing https scheme / normalize URL syntax#(lf)M071,Guatemala,Alternate1 Website,banrural.com.gt,https://banrural.com.gt,Add missing https scheme / normalize URL syntax#(lf)M071,Guatemala,Alternate2 Website,midinero.com.uy,https://midinero.com.uy,Add missing https scheme / normalize URL syntax#(lf)M072,Oman,App Website Link,omantel.om,https://omantel.om,Add missing https scheme / normalize URL syntax#(lf)M072,Oman,Alternate1 Website,paycash.com,https://paycash.com,Add missing https scheme / normalize URL syntax#(lf)M072,Oman,Alternate2 Name,Bank Muscat ,Bank Muscat,Trim whitespace / documented spelling or capitalization alias#(lf)M072,Oman,Alternate2 Website,bankmuscat.com,https://bankmuscat.com,Add missing https scheme / normalize URL syntax#(lf)M073,Venezuela,App Website Link,movilnet.net,https://movilnet.net,Add missing https scheme / normalize URL syntax#(lf)M073,Venezuela,Alternate1 Website,bancodevenezuela.com,https://bancodevenezuela.com,Add missing https scheme / normalize URL syntax#(lf)M073,Venezuela,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M074,Costa Rica,App Website Link,bcr.ro,https://bcr.ro,Add missing https scheme / normalize URL syntax#(lf)M074,Costa Rica,Alternate1 Website,baccredomatic.com,https://baccredomatic.com,Add missing https scheme / normalize URL syntax#(lf)M074,Costa Rica,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M075,Luxembourg,App Website Link,payconiq.com,https://payconiq.com,Add missing https scheme / normalize URL syntax#(lf)M075,Luxembourg,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M075,Luxembourg,Alternate2 Name,Twint,TWINT,Trim whitespace / documented spelling or capitalization alias#(lf)M075,Luxembourg,Alternate2 Website,twint.ch,https://twint.ch,Add missing https scheme / normalize URL syntax#(lf)M076,Croatia,App Website Link,aircash.eu,https://aircash.eu,Add missing https scheme / normalize URL syntax#(lf)M076,Croatia,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M076,Croatia,Alternate2 Website,vertexinc.com,https://vertexinc.com,Add missing https scheme / normalize URL syntax#(lf)M077,Panama,App Website Link,www.yappy.com.pa,https://www.yappy.com.pa,Add missing https scheme / normalize URL syntax#(lf)M077,Panama,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M077,Panama,Alternate2 Website,banistmo.com,https://banistmo.com,Add missing https scheme / normalize URL syntax#(lf)M078,Ivory Coast,App Website Link,orange.com,https://orange.com,Add missing https scheme / normalize URL syntax#(lf)M078,Ivory Coast,Alternate1 Website,momo.mtn.com,https://momo.mtn.com,Add missing https scheme / normalize URL syntax#(lf)M078,Ivory Coast,Alternate2 Website,momo.vn,https://momo.vn,Add missing https scheme / normalize URL syntax#(lf)M079,Sri Lanka,App Website Link,dialog.lk,https://dialog.lk,Add missing https scheme / normalize URL syntax#(lf)M079,Sri Lanka,Alternate1 Website,sampath.lk,https://sampath.lk,Add missing https scheme / normalize URL syntax#(lf)M079,Sri Lanka,Alternate1 Review,Sampath Bank Mobile App APK for Android - Download,https://sampath bank mobile app apk for android - download,Add missing https scheme / normalize URL syntax#(lf)M079,Sri Lanka,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M080,Turkmenistan,Alternate1 Website,asuda.gov.tm,https://asuda.gov.tm,Add missing https scheme / normalize URL syntax#(lf)M080,Turkmenistan,Alternate2 Website,e.gov.tm,https://e.gov.tm,Add missing https scheme / normalize URL syntax#(lf)M081,Lithuania,App Website Link,paysera.com,https://paysera.com,Add missing https scheme / normalize URL syntax#(lf)M081,Lithuania,Alternate1 Website,revolut.com,https://revolut.com,Add missing https scheme / normalize URL syntax#(lf)M081,Lithuania,Alternate2 Website,transfergo.com,https://transfergo.com,Add missing https scheme / normalize URL syntax#(lf)M082,Uruguay,App Website Link,dlocal.com,https://dlocal.com,Add missing https scheme / normalize URL syntax#(lf)M082,Uruguay,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M082,Uruguay,Alternate2 Website,abitab.com.uy,https://abitab.com.uy,Add missing https scheme / normalize URL syntax#(lf)M083,Serbia,App Website Link,dinersclub.com,https://dinersclub.com,Add missing https scheme / normalize URL syntax#(lf)M083,Serbia,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M083,Serbia,Alternate2 Website,pay.google.com,https://pay.google.com,Add missing https scheme / normalize URL syntax#(lf)M084,Tanzania,App Website Link,mpesa.com,https://mpesa.com,Add missing https scheme / normalize URL syntax#(lf)M084,Tanzania,Alternate1 Website,pesa.co,https://pesa.co,Add missing https scheme / normalize URL syntax#(lf)M084,Tanzania,Alternate2 Website,vodacom.co.tz,https://vodacom.co.tz,Add missing https scheme / normalize URL syntax#(lf)M085,Azerbaijan,App Website Link,anipay.az,https://anipay.az,Add missing https scheme / normalize URL syntax#(lf)M085,Azerbaijan,Alternate1 Website,click.uz,https://click.uz,Add missing https scheme / normalize URL syntax#(lf)M085,Azerbaijan,Alternate2 Website,azericard.com,https://azericard.com,Add missing https scheme / normalize URL syntax#(lf)M086,Ghana,App Website Link,momo.mtn.com,https://momo.mtn.com,Add missing https scheme / normalize URL syntax#(lf)M086,Ghana,Alternate1 Website,hubtel.com,https://hubtel.com,Add missing https scheme / normalize URL syntax#(lf)M086,Ghana,Alternate2 Website,airteltigo.com.gh,https://airteltigo.com.gh,Add missing https scheme / normalize URL syntax#(lf)M087,Slovenia,App Website Link,moneta.ru,https://moneta.ru,Add missing https scheme / normalize URL syntax#(lf)M087,Slovenia,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M087,Slovenia,Alternate2 Name,Google wallet,Google Wallet,Trim whitespace / documented spelling or capitalization alias#(lf)M087,Slovenia,Alternate2 Website,wallet.google/intl/,https://wallet.google/intl/,Add missing https scheme / normalize URL syntax#(lf)M088,Belarus,App Website Link,belkart.by,https://belkart.by,Add missing https scheme / normalize URL syntax#(lf)M088,Belarus,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M088,Belarus,Alternate2 Website,bank.yandex.ru/pay,https://bank.yandex.ru/pay,Add missing https scheme / normalize URL syntax#(lf)M089,DR Congo,App Website Link,mpesa.com,https://mpesa.com,Add missing https scheme / normalize URL syntax#(lf)M089,DR Congo,Alternate1 Website,orange.com,https://orange.com,Add missing https scheme / normalize URL syntax#(lf)M089,DR Congo,Alternate2 Website,velmie.com,https://velmie.com,Add missing https scheme / normalize URL syntax#(lf)M090,Myanmar,App Website Link,wavemoney.com.mm,https://wavemoney.com.mm,Add missing https scheme / normalize URL syntax#(lf)M090,Myanmar,Alternate1 Website,ongo.com.mm,https://ongo.com.mm,Add missing https scheme / normalize URL syntax#(lf)M090,Myanmar,Alternate2 Website,kbzpay.com,https://kbzpay.com,Add missing https scheme / normalize URL syntax#(lf)M091,Uganda,App Website Link,momo.mtn.com,https://momo.mtn.com,Add missing https scheme / normalize URL syntax#(lf)M091,Uganda,Alternate1 Website,airtel.co.ug,https://airtel.co.ug,Add missing https scheme / normalize URL syntax#(lf)M091,Uganda,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M092,Macau,App Website Link,macaupass.com,https://macaupass.com,Add missing https scheme / normalize URL syntax#(lf)M092,Macau,Alternate1 Website,alipay.com,https://alipay.com,Add missing https scheme / normalize URL syntax#(lf)M092,Macau,Alternate2 Website,pay.wechat.com,https://pay.wechat.com,Add missing https scheme / normalize URL syntax#(lf)M093,Cameroon,App Website Link,orange.com,https://orange.com,Add missing https scheme / normalize URL syntax#(lf)M093,Cameroon,Alternate1 Website,momo.mtn.com,https://momo.mtn.com,Add missing https scheme / normalize URL syntax#(lf)M093,Cameroon,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M094,Jordan,App Website Link,zaincash.iq,https://zaincash.iq,Add missing https scheme / normalize URL syntax#(lf)M094,Jordan,Alternate1 Website,pal.reflectapp.com,https://pal.reflectapp.com,Add missing https scheme / normalize URL syntax#(lf)M094,Jordan,Alternate2 Website,anypay.co.th,https://anypay.co.th,Add missing https scheme / normalize URL syntax#(lf)M095,Tunisia,App Review Link,Read 4 Flouci Reviews (2025) | flouci.com reviews,https://read 4 flouci reviews (2025) | flouci.com reviews,Add missing https scheme / normalize URL syntax#(lf)M095,Tunisia,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M095,Tunisia,Alternate2 Name,Twint,TWINT,Trim whitespace / documented spelling or capitalization alias#(lf)M095,Tunisia,Alternate2 Website,twint.ch,https://twint.ch,Add missing https scheme / normalize URL syntax#(lf)M096,Cambodia,App Website Link,pipay.com,https://pipay.com,Add missing https scheme / normalize URL syntax#(lf)M096,Cambodia,Alternate1 Website,ababank.com,https://ababank.com,Add missing https scheme / normalize URL syntax#(lf)M096,Cambodia,Alternate2 Website,wingbank.com.kh,https://wingbank.com.kh,Add missing https scheme / normalize URL syntax#(lf)M097,Bolivia,App Website Link,tigomoney.com,https://tigomoney.com,Add missing https scheme / normalize URL syntax#(lf)M097,Bolivia,Alternate1 Website,pagoefectivo.pe,https://pagoefectivo.pe,Add missing https scheme / normalize URL syntax#(lf)M097,Bolivia,Alternate2 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M098,Bahrain,App Website Link,benefit.bh,https://benefit.bh,Add missing https scheme / normalize URL syntax#(lf)M098,Bahrain,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M098,Bahrain,Alternate2 Website,tap.company,https://tap.company,Add missing https scheme / normalize URL syntax#(lf)M099,Latvia,App Website Link,swedbank.com,https://swedbank.com,Add missing https scheme / normalize URL syntax#(lf)M099,Latvia,Alternate1 Website,paypal.com,https://paypal.com,Add missing https scheme / normalize URL syntax#(lf)M099,Latvia,Alternate2 Name,Google wallet,Google Wallet,Trim whitespace / documented spelling or capitalization alias#(lf)M099,Latvia,Alternate2 Website,wallet.google/intl/,https://wallet.google/intl/,Add missing https scheme / normalize URL syntax#(lf)M100,Paraguay,App Website Link,Tigo Money,https://tigo money,Add missing https scheme / normalize URL syntax#(lf)M100,Paraguay,Alternate1 Website,personalpay.com,https://personalpay.com,Add missing https scheme / normalize URL syntax#(lf)M100,Paraguay,Alternate2 Website,visa.com,https://visa.com,Add missing https scheme / normalize URL syntax#(lf)\", TextEncoding.Utf8), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"country\", type text}, {\"field\", type text}, {\"original\", type text}, {\"cleaned\", type text}, {\"reason\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}